syslog-ng/alpine.dockerfile, syslog-ng/apkbuild/axoflow/syslog-ng/APKBUILD
Depends on syslog-ng/syslog-ng#4427
=> syslog-ng/apkbuild: add ebpf() module

.github/workflows/ssc-stable.yml, .github/workflows/syslog-ng-docker.yml, README.md, ssc/Dockerfile, syslog-ng/tests/smoke.sh
@fekete-robert Could you review the README, please? :)
https://github.com/MrAnno/syslog-ng-docker/blob/axosyslog/README.md
=> Rename to AxoSyslog

README.md
=> README: add deprecation info about syslog-ng image

.github/workflows/ssc-test.yml
There is an issue with pyyaml 5.4.1, see https://github.com/yaml/pyyaml/issues/728 for details
=> gha: fix ssc-test workflow

.github/workflows/ssc-stable.yml, .github/workflows/ssc-test.yml, .github/workflows/syslog-ng-docker.yml, .github/workflows/syslog-ng-snapshot.yml, syslog-ng/alpine.dockerfile
=> Minor fixes and image/ci updates

.github/workflows/syslog-ng-snapshot.yml
Keeping only the last 30 days (snapshot + snapshot-dbg images).
=> Autoremove old nightly images

.github/workflows/axosyslog-stable.yml
=> ci: fix typo

modules/http/http-worker.c
=> http: disable signal logic in libcurl

lib/filterx/CMakeLists.txt, lib/filterx/Makefile.am, lib/filterx/filterx-globals.c, lib/filterx/func-unset-empties.c, lib/filterx/func-unset-empties.h, lib/filterx/tests/CMakeLists.txt, lib/filterx/tests/Makefile.am, lib/filterx/tests/test_func_unset_empties.c, tests/light/functional_tests/filterx/test_filterx.py
Example config:
```
dict = json({"foo": "", "bar": "-", "baz": "N/A", "almafa": null, "kortefa": {"a":{"s":{"d":{}}}}, "szilvafa": [[[]]]});
unset_empties(dict);  # {}
list = json_array(["", "-", "N/A", null, {"a":{"s":{"d":{}}}}, [[[]]]]);
unset_empties(list);  # []
```
=> filterx: `unset_empties()`

packaging/debian/axosyslog-mod-common.maintscript
=> packaging: fix sql and mongodb preinst script

lib/filterx/filterx-scope.c
=> filterx: fix iterating on unset values in scope

lib/filterx/CMakeLists.txt, lib/filterx/Makefile.am, lib/filterx/filterx-globals.c, lib/filterx/func-str-transform.c, lib/filterx/func-str-transform.h
=> filterx: lower() and upper()

modules/json/filterx-cache-json-file.c
Signed-off-by: Szilard Parrag <szilard.parrag@axoflow.com>
=> filterx: fix crash if cache-json-file() fails

lib/filterx/object-json.c, lib/filterx/tests/test_object_json.c
=> filterx: support json() from LM_VT_STRING message_value

.github/workflows/upload-packages.yml
=> github-actions: fix bucket name in upload-packages

README.md
=> README: add notes about APT repo

.github/workflows/axosyslog-image-test.yml
@alltilla Implemented issue [docker image CVE scanning on CI](https://github.com/axoflow/axosyslog/issues/190)
=> ci: scan docker image on CVEs

dbld/build.manifest
https://github.com/MrAnno/axosyslog/actions/runs/9873055872
=> dbld: disable BPF on older platforms

NEWS.md, README.md
=> Fix readme

README.md
=> README: fix forked off from version

.github/workflows/test-apt-packages.yml
This reverts commit 476aabe5355343d774564ec5c36425cf410528fc.
=> Revert "github-actions: temp remove debian-testing official test"

.github/workflows/macos.yml, CMakeLists.txt, configure.ac, contrib/Brewfile, libtest/CMakeLists.txt, modules/grpc/otel/tests/Makefile.am, modules/kafka/CMakeLists.txt, modules/mqtt/CMakeLists.txt
Cherry-picked from syslog-ng/syslog-ng#5047 and syslog-ng/syslog-ng#5048 by @HofiOne
=> CMake and macOS build fixes

modules/xml/CMakeLists.txt, modules/xml/Makefile.am, modules/xml/filterx-parse-xml.c, modules/xml/filterx-parse-xml.h, modules/xml/tests/CMakeLists.txt, modules/xml/tests/Makefile.am, modules/xml/tests/test_filterx_parse_xml.c, modules/xml/xml-plugin.c, tests/copyright/policy, tests/light/functional_tests/filterx/test_filterx.py
=> filterx: `parse_xml()`

lib/filterx/expr-compound.c, lib/filterx/expr-generator.c, lib/filterx/filterx-grammar.ym, lib/filterx/object-message-value.c
=> filterx: fix some memory leaks

CMakeLists.txt, lib/template/tests/test_macro.c, modules/grpc/bigquery/bigquery-worker.cpp, modules/grpc/otel/filterx/object-otel-array.cpp, modules/grpc/otel/filterx/object-otel-array.hpp, modules/grpc/otel/filterx/object-otel-kvlist.cpp, modules/grpc/otel/filterx/otel-field.cpp
Cherry-picked from syslog-ng/syslog-ng#5092, syslog-ng/syslog-ng#5106, and syslog-ng/syslog-ng#5105 by @HofiOne
=> Build related fixes

.github/workflows/axosyslog-image-stable.yml
Preparation for automated rebuild.
=> ci: add AxoSyslog stable image workflow

modules/python-modules/syslogng/modules/s3/s3_destination.py
Cherry-picked from syslog-ng/syslog-ng#5137 by @HofiOne
=> s3: use python3.9 compatible glob()

modules/python-modules/syslogng/modules/s3/s3_destination.py, news/bugfix-318.md
=> S3 workaround comment and newsfile

packaging/package-indexer/indexer/deb_indexer.py
=> package-indexer: fix removing outdated nightly packages

lib/filterx/filterx-scope.c
- **lib/filterx: fix scope cloning**
- **lib/filterx: fix filterx_scope_foreach_variable**
=> Filterx: scope-sync followups for cloning

lib/CMakeLists.txt, lib/Makefile.am, lib/console.c, lib/console.h, lib/gprocess.c, lib/gprocess.h, syslog-ng/main.c
This PR is extracted from the syslog-ng-ctl attach PR to make it easier to review and to decouple another PR from the huge series.
=> Add console management

charts/axosyslog/Chart.yaml
=> helm-charts: update to 4.9.0

lib/cfg-block-generator.c, lib/cfg-block-generator.h, lib/cfg-block.c, lib/cfg-parser.c, lib/cfg-parser.h, modules/appmodel/app-object-generator.c, modules/appmodel/app-object-generator.h, modules/appmodel/app-transform-generator.c, modules/appmodel/appmodel-grammar.ym, modules/appmodel/transformation.c, modules/appmodel/transformation.h, modules/confgen/confgen-plugin.c, modules/python/python-confgen.c
Example usage:
`syslog-ng.conf`:
```
transformation "app-1"[default] {
transform[transform-1] {
step["transform-1-step-1"] {
};
step["transform-1-step-2"] {
};
};
transform[transform-2] {
step["transform-2-step-1"] {
};
step["transform-2-step-2"] {
};
};
transform[transform-3] {
step["transform-3-step-1"] {
};
step["transform-3-step-2"] {
};
};
};
log {
source { example-msg-generator(); };
parser {
app-transform(filterx-app-variable(meta.app) include-transforms(transform_1, transform_2) exclude-transforms(transform_1));
};
};
```
```
$ syslog-ng -Fe --preprocess-into=-
Setting current version as config version; version='4.9'
transformation "app-1"[default] {
transform[transform-1] {
step["transform-1-step-1"] {
#
};
step["transform-1-step-2"] {
#
};
};
transform[transform-2] { …
```
=> `app-transform()`: add `include-transforms()` and `exclude-transforms()` options

lib/logpipe.c
Not relevant since:
e8fefcfce46700572cfddf89c97a13e1a64fcaaf
=> logpipe: remove out-of-date comment

modules/json/filterx-cache-json-file.c
=> filterx: fix `cache_json_file()` error reporting

dbld/images/devshell.dockerfile, dbld/packages.manifest, dbld/rules
This reverts commit 7dc49d02edf003a831fd8bdddd106eba2cd02264.
=> Revert "dbld: change devshell to use ubuntu-noble as base"

news/fx-feature-435.md
=> news: filterx keys function

.github/workflows/axosyslog-image-test.yml
Similarly to https://github.com/kube-logging/fluentd-images/pull/157
=> CI: fix trivy java DB location

lib/filterx/expr-null-coalesce.c, lib/filterx/func-set-fields.c
=> filterx: `set_fields()` trace and debug logs

.github/workflows/upload-packages.yml
`aws` command tested locally with a private R2 instance.
I hope this is the last place we need to do this.
=> github-actions: upload packages disable checksum validation

lib/filterx/expr-regexp-search.c, lib/filterx/filterx-object.c, lib/filterx/func-sdata.c, lib/filterx/func-vars.c, lib/filterx/object-metrics-labels.c, modules/cef/event-format-parser.c, modules/grpc/otel/filterx/object-otel-kvlist.cpp, modules/grpc/otel/filterx/otel-field.cpp, modules/kvformat/filterx-func-parse-kv.c
=> filterx: stack allocated string followups

lib/filterx/filterx-globals.c, lib/filterx/filterx-globals.h, lib/filterx/filterx-ref.c, lib/filterx/filterx-ref.h, lib/filterx/object-list-interface.c, lib/filterx/object-primitive.c, lib/filterx/object-primitive.h, lib/filterx/object-string.c, lib/filterx/object-string.h
This PR moves a number of filterx functions to be inline.
=> Filterx inline functions

modules/grpc/Makefile.am, modules/grpc/pubsub/filterx/object-pubsub-message.cpp, modules/grpc/pubsub/filterx/object-pubsub-message.hpp
pubsub_message() lacks a repr method, let's add that.
This also fixes a minor issue in the pubsub Makefile.
=> Filterx implement repr for pubsub message

lib/filterx/CMakeLists.txt, lib/filterx/Makefile.am, lib/filterx/filterx-globals.c, lib/filterx/func-set-timestamp.c, lib/filterx/func-set-timestamp.h, lib/filterx/object-datetime.c, news/fx-feature-510.md, tests/light/functional_tests/filterx/test_filterx.py
Example usage:
```
set_timestamp(datetime, "stamp");
```
=> Filterx set timestamp func

.github/workflows/axosyslog-docker.yml, .github/workflows/axosyslog-image-snapshot.yml
=> ci: allow non-overridable custom tags for snapshot images 

lib/filterx/CMakeLists.txt, lib/filterx/Makefile.am, lib/filterx/filterx-globals.c, lib/filterx/func-set-pri.c, lib/filterx/func-set-pri.h, lib/filterx/func-set-timestamp.c, news/fx-feature-521.md, tests/light/functional_tests/filterx/test_filterx.py
Example usage:
```
set_pri(pri="100");
```
Note: Second argument must be between 0 and 191 inclusive.
=> Filterx set pri func

news/other-531.md, scl/azure/azure-monitor.conf
=> `azure-monitor()` news entry

.github/workflows/axosyslog-nightly.yml
=> github-actions: keep nightly docker images for 2 months

modules/appmodel/app-transform-generator.c, modules/appmodel/tests/CMakeLists.txt, modules/appmodel/tests/Makefile.am, modules/appmodel/tests/test_app_transform_generator.c, tests/copyright/policy
Renamed the flavour field in app_transform to topic and ensured it is referred to as topic throughout. This improves consistency between app-transform and app-parser.
app-transform functionality also covered with unit tests.
=> App transform topic

tests/copyright/policy, tests/light/functional_tests/Makefile.am, tests/light/functional_tests/source_drivers/unix_dgram_source/test_unix_dgram_source_acceptance.py, tests/light/pyproject.toml, tests/light/src/axosyslog_light/Makefile.am, tests/light/src/axosyslog_light/driver_io/unix_dgram/unix_dgram_io.py, tests/light/src/axosyslog_light/syslog_ng_config/statements/sources/unix_dgram_source.py, tests/light/src/axosyslog_light/syslog_ng_config/syslog_ng_config.py
=> light: `UnixDgramSource`

tests/light/pyproject.toml, tests/light/src/axosyslog_light/syslog_ng/syslog_ng.py, tests/light/src/axosyslog_light/syslog_ng_config/syslog_ng_config.py
=> light: make some variables protected from private

lib/filterx/filterx-globals.c, lib/filterx/filterx-globals.h, lib/filterx/object-datetime.c, lib/filterx/object-datetime.h, lib/filterx/object-string.c
=> Filterx cache datetime zero

lib/file-monitor.c, lib/filterx/func-cache-json-file.c, news/bugfix-612-2.md, news/fx-bugfix-612.md, tests/copyright/policy, tests/light/functional_tests/Makefile.am, tests/light/functional_tests/filterx/test_filterx_cache_json_file.py
1b13018742fa49c7d75cb88b75bdf9e8c89ffe8f removed the basename.
=> file-monitor: fix inotify

lib/filterx/expr-compound.c, lib/filterx/expr-literal-container.c, lib/filterx/filterx-object.h, lib/filterx/filterx-ref.c, lib/filterx/filterx-ref.h, lib/filterx/func-sdata.c, lib/filterx/json-repr.c, lib/filterx/tests/test_object_cow.c
This PR is opened in response to https://github.com/axoflow/axosyslog/pull/581#discussion_r2048824282.
I am merging that PR (#581) as I have a lot of dependencies that build on top of that, but take the discussion into this PR.
@MrAnno 
This needs to be on top of #594 due to new code that is not yet on main.
=> Filterx refine cow wrap naming

tests/light/src/axosyslog_light/helpers/loggen/loggen.py
- the helper function will parse and save last line of loggen output
=> light: Extend Loggen() with get_loggen_stats() function

lib/cfg-grammar.y, lib/cfg-lex.l, lib/cfg-lexer.h, lib/filterx/filterx-grammar.ym
Preparation for the division operator.
=> filterx: allow parsing '/' operator

lib/filterx/object-metrics-labels.c, tests/light/functional_tests/filterx/test_filterx_funcs.py
When `{...}` was still a generator the `metrics_labels({...})` expression was handled by `generator_casted_assignment`.
Since #594, `{...}` is a real object, so the generic `function_call` rule gets invoked, and `{...}` is passed as an argument.
We need to prepare `metrics_labels()` for this.
No news file is needed, we did not release #594 yet.
=> filterx/metrics-labels: fix ctor with dict

lib/cfg-grammar.y, lib/filterx/CMakeLists.txt, lib/filterx/Makefile.am, lib/filterx/expr-arithmetic-operators.c, lib/filterx/expr-arithmetic-operators.h, lib/filterx/filterx-grammar.ym, news/fx-feature-625.md, tests/light/functional_tests/filterx/test_filterx.py
Examples:
```
if (3 - 3 == 0)
if (3.0 * 3 == 9.0)
if (3.0 / 3.0 == 1.0)
if (4 % 3 == 1)
```
=> Filterx add arithmetic operators

.github/workflows/axosyslog-builder.yml
=> docker: quickfix for the early merge of #644

modules/grpc/pubsub/pubsub-dest.hpp
=> pubsub: fix double free

modules/xml/CMakeLists.txt, modules/xml/Makefile.am, modules/xml/filterx-func-format-windows-eventlog-xml.c, modules/xml/filterx-func-format-windows-eventlog-xml.h, modules/xml/filterx-func-format-xml.c, modules/xml/filterx-func-format-xml.h, modules/xml/xml-plugin.c, news/fx-feature-684.md, tests/light/functional_tests/filterx/test_filterx.py
Example:
$MSG = format_xml({"a":{"b":"foo"}});
=> Filterx add format xml

scl/cisco/plugin.conf
Cherry-picked from syslog-ng/syslog-ng#5410
=> feat(scl/cisco): add support for Cisco Nexus NXOS 9.3 syslog format

tests/copyright/policy, tests/light/pyproject.toml, tests/light/shared_files/gdb_exec.sh, tests/light/src/axosyslog_light/executors/process_executor.py, tests/light/src/axosyslog_light/fixtures.py, tests/light/src/axosyslog_light/syslog_ng/syslog_ng.py, tests/light/src/axosyslog_light/syslog_ng/syslog_ng_local_executor.py
- light: bump version to 1.9.0
- light/syslog-ng: Mark process as None during a detected crash
- light/ProcessExecutor: print a debug log why process can not started
- light/Start Parameter: add gdb_for_bt as a new --run-under start parameter
=> light: Add various improvements

charts/axosyslog/Chart.yaml, charts/axosyslog/templates/collector-config.yaml, charts/axosyslog/values.yaml, modules/python-modules/syslogng/modules/kubernetes/scl/kubernetes.conf
=> charts: add maxContainers option to Kubernetes source

modules/grpc/common/metrics/grpc-metrics.cpp, modules/grpc/common/metrics/grpc-metrics.hpp, news/bugfix-754.md
=> `grpc`: fix dest metrics race

.github/workflows/axosyslog-builder.yml, docker/axosyslog-builder.dockerfile, docker/axosyslog.dockerfile
Depends on https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/88787
https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/88929
=> axosyslog-builder cleanup

lib/logreader.c, lib/logscheduler.c, lib/logwriter.c, lib/mainloop-io-worker.c, lib/mainloop-io-worker.h, lib/timeutils/cache.c, lib/timeutils/format.c, lib/timeutils/tests/Makefile.am, lib/timeutils/tests/test_cache.c
These add a few patches that are the result of my tests to improve scalability.  I have some more lined up.
=> Lock contention improvements

tests/light/pyproject.toml, tests/light/src/axosyslog_light/syslog_ng_config/renderer.py, tests/light/src/axosyslog_light/syslog_ng_config/statements/logpath/logpath_if.py, tests/light/src/axosyslog_light/syslog_ng_config/syslog_ng_config.py
=> light: add logpath level if-elif-else blocks 

.github/workflows/macos.yml, libtest/queue_utils_lib.c, libtest/queue_utils_lib.h, modules/diskq/diskq-options.c, modules/diskq/diskq-options.h, modules/diskq/diskq.c, modules/diskq/logqueue-disk-non-reliable.c, modules/diskq/logqueue-disk-non-reliable.h, modules/diskq/logqueue-disk-reliable.c, modules/diskq/logqueue-disk.c, modules/diskq/logqueue-disk.h, modules/diskq/tests/test_diskq_full.c, modules/diskq/tests/test_diskq_tools.h
=> Fix disk-buffer getting stuck on serialization failure and losing messages with misconfigured flow-control
