axoflow/axosyslog

syslog-ng/apkbuild/axoflow/syslog-ng/APKBUILD

Followup for https://github.com/syslog-ng/syslog-ng/pull/4534.

axosyslog: add scl.conf to scl package

---

syslog-ng/apkbuild/axoflow/syslog-ng/APKBUILD

syslog-ng: use bundled ivykis

---

.github/workflows/ssc-stable.yml
.github/workflows/syslog-ng-docker.yml
syslog-ng/alpine.dockerfile

The labels introduced in #45 are [not shown on ghcr.io](https://github.com/axoflow/axosyslog-docker/pkgs/container/axosyslog/131605762?tag=4.4.0) because for mult-arch images the `description` field should be filled [differently](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#adding-a-description-to-multi-arch-images).
Once the release job in my fork has finished running I'll link it to help with the review.
EDIT: forked release: https://github.com/overorion/axosyslog-docker/pkgs/container/axosyslog/135500889?tag=4.4.0-oci4

Multi arch OCI description fix

---

.github/workflows/syslog-ng-docker.yml

In #49 the description was fixed for the stable release, however the metadata generation step is skipped during the nightly release, resulting in CI failure: https://github.com/axoflow/axosyslog-docker/actions/runs/6540259820
This PR enables that step regardless of the release type, so the required field will be filled.
See this workflow run: https://github.com/OverOrion/axosyslog-docker/actions/runs/6545245211

gha: add metadata extraction step during nightly release as well

---

syslog-ng/alpine.dockerfile

This is a workaround for CVE-2023-43804 by upgrading urllib3

syslog-ng: add workaround for CVE-2023-43804

---

.github/workflows/axosyslog-collector.yml
.github/workflows/release-charts.yml
.github/workflows/release.yml
LICENSE
README.md
charts/axosyslog-collector/.helmignore
charts/axosyslog-collector/Chart.yaml
charts/axosyslog-collector/README.md
charts/axosyslog-collector/templates/NOTES.txt
charts/axosyslog-collector/templates/_helpers.tpl
charts/axosyslog-collector/templates/clusterrole.yaml
charts/axosyslog-collector/templates/clusterrolebinding.yaml
charts/axosyslog-collector/templates/config.yaml
charts/axosyslog-collector/templates/daemonset.yaml
charts/axosyslog-collector/templates/podmonitor.yaml
charts/axosyslog-collector/templates/scc.yaml
charts/axosyslog-collector/templates/service.yaml
charts/axosyslog-collector/templates/serviceaccount.yaml
charts/axosyslog-collector/values.yaml

This PR contains the merge of axosyslog-charts, so that both would be available in the same repository.
The only conflicts have been on:
* LICENSE: both are now Apache v2.0
* README.md: information on both parts of the repository are now part of the README.
As a next step I intend to rename this repository to "axosyslog" and make sure every github action works as expected.

Merge axosyslog-charts

---

README.md
syslog-ng/apkbuild/axoflow/syslog-ng/APKBUILD

Bump the versions so we can release the AxoSyslog container as well.

all: bump version numbers to 4.6.0

---

syslog-ng/python-modules/webhook/scl/webhook.conf
syslog-ng/python-modules/webhook/source.py

Depends on syslog-ng/syslog-ng 4964

syslog-ng/webhook: add SOURCEIP and URL path+query param enrichment

---

.github/workflows/axosyslog-charts-lint.yml
.github/workflows/axosyslog-charts-release.yml
README.md
charts/LICENSE
docker/LICENSE

docker directory: from GPL-3.0-or-later to GPL-2.0-or-later
main author: @MrAnno, based on the official Alpine syslog-ng packaging
charts directory: from Apache-2.0 to GPL-2.0-or-later
main author: @alltilla
Our intention with the license change is to use a single license in the entire AxoSyslog repository, also aligning it with the license of the syslog-ng source code for clarity.
@alltilla Please take a look at this; is this what we agreed upon?

charts/docker: relicense under GPL-2.0-or-later

---

packaging/package-indexer/Dockerfile
packaging/package-indexer/cdn/__init__.py
packaging/package-indexer/cdn/azure_cdn.py
packaging/package-indexer/cdn/cdn.py
packaging/package-indexer/cdn/cloudflare_cdn.py
packaging/package-indexer/indexer/deb_indexer.py
packaging/package-indexer/pyproject.toml
packaging/package-indexer/remote_storage_synchronizer/__init__.py
packaging/package-indexer/remote_storage_synchronizer/azure_container_synchronizer.py
packaging/package-indexer/remote_storage_synchronizer/remote_storage_synchronizer.py
packaging/package-indexer/remote_storage_synchronizer/s3_bucket_synchronizer.py
tests/copyright/policy

Not my proudest commit history, sorry.

package-indexer: S3 and Cloudflare

---

lib/filterx/object-dict-interface.c
lib/filterx/object-dict-interface.h
lib/filterx/object-json.c
lib/filterx/object-list-interface.c
lib/filterx/object-list-interface.h
modules/grpc/otel/filterx/object-otel-array.cpp
modules/grpc/otel/filterx/object-otel-kvlist.cpp
modules/grpc/otel/filterx/object-otel-logrecord.cpp
modules/grpc/otel/filterx/object-otel-logrecord.hpp
modules/grpc/otel/filterx/object-otel-resource.cpp
modules/grpc/otel/filterx/object-otel-resource.hpp
modules/grpc/otel/filterx/object-otel-scope.cpp
modules/grpc/otel/filterx/object-otel-scope.hpp
modules/grpc/otel/filterx/otel-field.cpp
modules/grpc/otel/filterx/otel-field.hpp
modules/grpc/otel/filterx/protobuf-field.cpp
modules/grpc/otel/filterx/protobuf-field.hpp
modules/grpc/otel/tests/test-otel-filterx.cpp
tests/light/functional_tests/filterx/test_filterx.py

filterx: otel dict

---

lib/filterx/CMakeLists.txt
lib/filterx/Makefile.am
lib/filterx/expr-plus.c
lib/filterx/expr-plus.h
lib/filterx/filterx-grammar.ym

This is just a skeleton for '+' operator that allows the concatenation of strings.

filterx: add a '+' operator skeleton that works on strings

---

modules/appmodel/CMakeLists.txt
modules/appmodel/Makefile.am
modules/appmodel/app-object-generator.c
modules/appmodel/app-object-generator.h
modules/appmodel/app-parser-generator.c
modules/appmodel/application.c
modules/appmodel/application.h
modules/appmodel/appmodel-context.c
modules/appmodel/appmodel-context.h
modules/appmodel/appmodel-grammar.ym
modules/appmodel/appmodel.c
modules/appmodel/appmodel.h
modules/appmodel/tests/test_app_parser_generator.c
modules/appmodel/tests/test_application.c
modules/appmodel/tests/test_appmodel.c
modules/appmodel/tests/test_appmodel_context.c

This PR refactors the app-parser() and has the following changes:
1)  it gets rid off the "*" topic, which basically allowed applications to register to all topics. This does not make much sense for me now, and as far as I understand noone is using it and is undocumented. The only big user is sc4s.
2)    it creates the possibility to create app-parser() like entities by extracting an AppModelObject base class.
3)    it has some refactors as well

App parser refactor

---

lib/filterx/expr-comparison.c
lib/filterx/expr-function.c
lib/filterx/expr-function.h
lib/filterx/object-json-array.c
lib/filterx/object-json-object.c
lib/filterx/object-json.c
lib/filterx/object-primitive.c
lib/filterx/object-string.c
lib/filterx/tests/test_expr_comparison.c
lib/filterx/tests/test_object_boolean.c
lib/filterx/tests/test_object_bytes.c
lib/filterx/tests/test_object_datetime.c
lib/filterx/tests/test_object_double.c
lib/filterx/tests/test_object_integer.c
lib/filterx/tests/test_object_json.c
lib/filterx/tests/test_object_message.c
lib/filterx/tests/test_object_null.c
lib/filterx/tests/test_object_protobuf.c

filterx: various small fixes

---

lib/timeutils/cache.c
modules/syslogformat/syslog-format.c

This improves the caching in  cached_mktime() so that a single real mktime() invocation is valid for up to an hour.

Improve mktime cache

---

lib/cfg-grammar.y
lib/filter/filter-expr-grammar.ym
tests/copyright/policy
tests/light/functional_tests/Makefile.am
tests/light/functional_tests/filters/test_multiple_filters.py

In 6d74e60c4b2b51e9842ccab23902803b9ff8de2b, the precedence of ';' has implicitly changed for filter rules, changing the meaning of filter expressions:
The expression `not program("a"); message("b");` should have the following interpretation: `(not program("a")) and message("b")`.
Due to accidentally changed precedence of ';', currently it is interpreted as `not (message("a") and message("b"))`.
This patch recovers the original precedence, but also introduces precedence and left associativity for other semicolon-separated rules.
All the other (non-filter) uses of the ';' token are unambiguous, so this declaration won't interfere with those rules.
Related issue https://github.com/syslog-ng/syslog-ng/issues/4980

filters: fix the precedence of ';'

---

modules/diskq/qdisk.c

As reported by @akunszt, this should fix creating disk buffer files on NFS.

Open qdisk dirlock in rw mode

---

lib/stats/stats-query.c
lib/stats/stats-registry.c
news/bugfix-129-2.md
news/bugfix-129.md

All new counters should have their names filled.
`g_pattern_spec_match_string: assertion 'string != NULL' failed`

stats-query: fix assert and showing timestamps 

---

lib/filterx/filterx-eval.c
lib/filterx/filterx-weakrefs.c
lib/filterx/object-json-array.c
lib/filterx/object-json-object.c
lib/filterx/object-json.c
lib/filterx/object-json.h
modules/json/filterx-cache-json-file.c

filterx: `cache_json_file()` deep freeze

---

lib/filterx/expr-getattr.c
tests/light/functional_tests/filterx/test_filterx.py

This adds support for isset() on attribute expressions, e.g.
isset(meta.foobar);
This was missed when isset() was implemented, we only have it for subscript access and variables.

Filterx is set for getattr

---

lib/driver.c
lib/logthrdest/logthrdestdrv.c
news/bugfix-128.md

This fixes a crash when init() fails on a disk-buffered destination:
> modules/diskq/logqueue-disk.c:127:log_queue_disk_free_method:
> assertion failed: (!qdisk_started(self->qdisk))

driver: release the queues of half-initialized pipes 

---

lib/cfg-grammar.y

Whenever we have an embedded block in a source/destination/parser/rewrite block, we did not push the log context while parsing those elements.
This prevented us from using "block log" elements in these contexts.
Fix that up.

cfg-grammar: fix context for looking up blocks

---

.github/workflows/create-packages.yml
.github/workflows/dbld-images.yml
.github/workflows/packages.yml
dbld/Makefile.am
dbld/build.manifest
dbld/builddeps
dbld/images/almalinux-9.dockerfile
dbld/rules
packaging/rhel/axosyslog.spec

Please don't merge until rpms are built and I can test them.

packaging/rhel: add fixes to adjust to AlmaLinux:9

---

modules/python-modules/syslogng/modules/s3/s3_destination.py
modules/python-modules/syslogng/modules/s3/s3_object.py
modules/python-modules/syslogng/modules/s3/scl/s3.conf

This PR enables to use the server side encryption on the s3() destination. It is a common pattern that data stored on the S3 bucket is encrypted at the rest.
S3 supports multiple server side encryption possibilities. This is only for the `aws:kms` method. In theory `aws:kms:dsse` should also work but as it uses the same arguments but I didn't test it so I disabled that intentionally.
Check the [s3api](https://docs.aws.amazon.com/cli/latest/reference/s3api/create-multipart-upload.html) documentation for the details.
This means that the server-side-encryption() option accepts only `aws:kms` or an empty string, which is the default.
The kms-key() should be:
* an ID of a key
* an alias of a key, but in that case you have to add the `alias/` prefix
* an ARN of a key
For example:
``` …
```

s3: add server side encryption support

---

lib/cfg-grammar.y
lib/cfg-lex.l
lib/cfg-lexer.c
lib/cfg-lexer.h
lib/cfg-source.c
lib/pragma-grammar.ym
lib/tests/test_lexer.c
modules/appmodel/app-parser-generator.c
modules/appmodel/application.c
modules/appmodel/application.h
modules/appmodel/appmodel-grammar.ym
modules/appmodel/tests/test_application.c

This improves filterx expression representation in trace level logs by improving the location tracking for filterx source text.
This will also cause any source related displays (e.g. error output or the filterx expression display) to use the _postprocessed_ output, e.g. the text _after_ substitution, instead of the original text read from the source file.
This makes it easier to find issues that are related to parts substituted from parameters/environment variables.
This sits on top of the app-transform() branch

Filterx expr location fixes

---

modules/csvparser/CMakeLists.txt
modules/csvparser/Makefile.am
modules/csvparser/csvparser-plugin.c
modules/csvparser/filterx-func-format-csv.c
modules/csvparser/filterx-func-format-csv.h
modules/csvparser/tests/CMakeLists.txt
modules/csvparser/tests/Makefile.am
modules/csvparser/tests/test_filterx_func_format_csv.c
tests/copyright/policy

add csv formatter function to filterx, helps re-format csv data parsed by parse_csv previously
- also accepts json_array and json_object as input which are the possible output types for parse_csv filter func
- supports optional named argument for delimiter character
- supports optional columns argument with json_object input type for column filtering/ordering
- ignores column names with json_array input
-  uses json_object's key ordering when column names are not set (which is seemingly correct order)
-  auto double-quotes column values when they contain delimiter character
- auto escapes double quotes when double-quoting a column value
examples:
```
filterx {
...
x = parse_csv($MSG); # returns json_array as '["foo","bar","baz"]'
$MSG = format_csv(x, delimiter=","); # custom delimiter
... …
```

Filterx format csv

---

lib/filterx/CMakeLists.txt
lib/filterx/Makefile.am
lib/filterx/filterx-globals.c
lib/filterx/filterx-scope.c
lib/filterx/filterx-scope.h
lib/filterx/func-vars.c
lib/filterx/func-vars.h
tests/light/functional_tests/filterx/test_filterx.py

This function gathers all filterx variables to a json object. Similar to the python vars() function without arguments. https://docs.python.org/3/library/functions.html#vars

filterx: add vars() function 

---

lib/filterx/expr-comparison.c

Unfortunately without this patch $PROGRAM == "program" will never be true, as $PROGRAM will be a message-value and "program" is a literal string. And type aware comparisons did not unmarshal its argument.
Do so now.

filterx/expr-comparison: use typed values for comparisons

---

lib/cfg-lex.l

This PR fixes the filterx identifier pattern in the lexer to allow a leading underscore.

cfg-lex.l: allow an underscore in identifier names

---

lib/cfg-grammar.y

This will add location information to the grammar debug output.

cfg-grammar.y: add location reporting to bison debug

---

modules/grpc/otel/filterx/object-otel-kvlist.cpp

otel: filterx kv-list get_subscript now returns hard NULL on missing key

fix: otel kvlist get_subscript

---

lib/filterx/filterx-grammar.ym

Sometimes constructing a generator can fail (for example regexp_search()),  which the grammar needs to handle to avoid a crash at startup.

filterx: handle failures from generator constructors

---

lib/filterx/expr-function.c
lib/filterx/expr-function.h
modules/csvparser/filterx-func-format-csv.c
modules/csvparser/filterx-func-format-csv.h
modules/csvparser/tests/test_filterx_func_format_csv.c

- format function now renders additional columns as default value // ["foo","bar","baz","",""]
- introduce "default_value" named argument to change the value of default value
- sets the default of default_value to "" on construct

Format csv refinement changes

---

modules/affile/poll-file-changes.c
modules/affile/poll-file-changes.h
modules/affile/tests/Makefile.am
modules/affile/tests/test_wildcard_file_reader.c
modules/affile/wildcard-file-reader.c
modules/affile/wildcard-file-reader.h
news/bugfix-160.md

This patch fixes a "race condition" between the EOF and file deletion
detection of AxoSyslog when wildcard-file() is used.
If a file is written after being deleted (an application keeps an fd
open), or if these two events occur concurrently, nearly at the same
time, the file poller mechanism might schedule another read cycle while
the file has already been marked as fully read and deleted.
To avoid scheduling issues between the two checks, the following is done
from now on: We do not track the EOF state in the WildcardFileReader,
instead, when a file deletion notification is received, the poller will
be instructed to stop after reaching the next EOF, and only then will
AxoSyslog actually delete the reader instance.
Fixxes syslog-ng/syslog-ng#4989

wildcard-file: fix race between EOF and file deletion detection 

---

.github/workflows/axosyslog-charts-release.yml
.github/workflows/axosyslog-docker.yml
.github/workflows/axosyslog-image-snapshot.yml
.github/workflows/axosyslog-nightly.yml
.github/workflows/axosyslog-stable.yml
.github/workflows/comment-on-version-bump-pr.yml
.github/workflows/dbld-images.yml
.github/workflows/draft-release.yml
.github/workflows/version-bump.yml

> For each of the available scopes, shown in the table below, you can assign one of the permissions: read, write, or none. If you specify the access for any of these scopes, all of those that are not specified are set to none.
I used `write-all` for the above reason (to avoid specifying all scopes one by one for each job), but if needed, I can fine-grain them. Note that the current permissions are stricter (even with `write-all`) than the previous defaults.

ci: set write permissions explicitly for jobs

---

modules/rate-limit-filter/rate-limit-parser.c
news/bugfix-169.md

Originally reported by @nivelus in https://github.com/syslog-ng/syslog-ng/issues/5001

rate-limit: parse error segfault fix

---

lib/cfg-grammar.y
lib/cfg-lex.l
lib/filterx/CMakeLists.txt
lib/filterx/Makefile.am
lib/filterx/expr-null-coalesce.c
lib/filterx/expr-null-coalesce.h
lib/filterx/filterx-eval.h
lib/filterx/filterx-expr.c
lib/filterx/filterx-grammar.ym
lib/filterx/tests/CMakeLists.txt
lib/filterx/tests/Makefile.am
lib/filterx/tests/test_expr_null_coalesce.c
libtest/filterx-lib.c
libtest/filterx-lib.h
modules/kvformat/tests/test_filterx_func_format_kv.c
tests/light/functional_tests/filterx/test_filterx.py

Add null coalesce operator to simplify handling of default values.  Suppresses errors occurring in the LHS argument, but logs them for debugging purposes.
```
filterx {
key_na = "wrong";
key = "bar";
data = json({"foo":"1", "bar":"2", "baz":"3"});
x = data[key_na] ?? "default";
y = null ?? data[key];
z = data[key_na] ?? data[key] ?? "default";
}
```

Filterx null coalesce operator

---

lib/template/macros.c
news/bugfix-162.md

`MESSAGE` in particular can contain not just string data, but for example JSON as well.
This is necessary for the `$(format-json)` function to work properly with a json type `MESSAGE`.
Kudos to b1oodborne from Discord for finding this issue.

macros: extract type information from MESSAGE, PROGRAM and HOST 

---

lib/filterx/expr-condition.c
lib/filterx/tests/test_expr_condition.c

filterx: change condition's statments execution's error result from FALSE to NULL

filterx condition error handling quick fix

---

lib/compat/cpp-start.h
modules/grpc/otel/filterx/object-otel-kvlist.cpp
modules/grpc/protos/CMakeLists.txt
modules/grpc/protos/Makefile.am

```
/usr/include/json-c/json_object.h:473:55: warning: "__STDC_VERSION__" is not defined, evaluates to 0 [-Wundef]
```
---
```
./modules/grpc/protos/google-proto/google/api/client.pb.cc: In member function ‘virtual google::protobuf::uint8* google::api::CommonLanguageSettings::_InternalSerialize(google::protobuf::uint8*, google::protobuf::io::EpsCopyOutputStream*) const’:
./modules/grpc/protos/google-proto/google/api/client.pb.cc:801:31: warning: ‘const string& google::api::CommonLanguageSettings::reference_docs_uri() const’ is deprecated [-Wdeprecated-declarations]
801 |   if (this->reference_docs_uri().size() > 0) {
|       ~~~~~~~~~~~~~~~~~~~~~~~~^~
In file included from ./modules/grpc/protos/google-proto/google/api/client.pb.cc:4: …
```

compat, grpc: fix C++ build warnings

---

lib/filterx/object-datetime.c
lib/filterx/tests/test_object_datetime.c
tests/light/functional_tests/filterx/test_filterx.py

Whenever a datetime object is to be represented in JSON, we should not add the timezone value.

Filterx datetime in json should be represented as epoch

---

lib/apphook.c
lib/metrics/CMakeLists.txt
lib/metrics/Makefile.am
lib/metrics/metrics-template.c
lib/metrics/metrics-template.h
lib/metrics/metrics-tls-cache.c
lib/metrics/metrics-tls-cache.h
lib/metrics/metrics.c
lib/metrics/metrics.h
modules/metrics-probe/metrics-probe.c
tests/copyright/policy

metrics: factor out TLS cache

---

lib/metrics/CMakeLists.txt
lib/metrics/Makefile.am
lib/metrics/metrics-cache.c
lib/metrics/metrics-cache.h
lib/metrics/metrics-template.c
lib/metrics/metrics-tls-cache.c
lib/metrics/metrics-tls-cache.h
modules/http/http-worker.c
modules/http/http-worker.h
tests/copyright/policy

We do not show the orphaned metrics in the prometheus stats output. Registering, incrementing then unregistering the counter makes it orphaned.
This can be solved with binding the lifecycle of the counters to the worker.
No news file entry is needed, the counters disappeared after 4.7 was released.

http: bind `output_http_requests_total` counter lifecycle to worker's 

---

lib/cfg-lex.l
tests/light/functional_tests/filterx/test_filterx.py

lexer was unable to handle escaped slashes in slash strings ( i.e: \foo/\bar\ ) this lesser refinement of lexer rule for slash strings allows the lexer to recognize escaped slashes

lexer fix for slash strings

---

.github/workflows/axosyslog-nightly.yml
.github/workflows/draft-release.yml
.github/workflows/index-packages.yml
.github/workflows/test-apt-packages.yml
.github/workflows/upload-packages.yml
packaging/package-indexer/config/config.py
packaging/package-indexer/index-packages.py
packaging/package-indexer/indexer/apt_conf/nightly.conf
packaging/package-indexer/indexer/apt_conf/stable.conf
packaging/package-indexer/indexer/deb_indexer.py

Depends on #107 
Example config:
```
storage:
vendor: "s3"
incoming:
all:
endpoint: "https://foobar.r2.cloudflarestorage.com"
bucket: "axosyslog-apt-incoming"
access-key: "foobar"
secret-key: "foobar"
indexed:
all:
endpoint: "https://foobar.r2.cloudflarestorage.com"
bucket: "axosyslog-apt-indexed"
access-key: "foobar"
secret-key: "foobar"
cdn:
vendor: "cloudflare"
all:
zone-id: "foobar"
api-token: "foobar"
gpg-key-path: "/home/runner/work/axosyslog/axosyslog/packaging/package-indexer/axosyslog_signing_key.sub.priv.asc"
```
Example run: https://github.com/alltilla/axosyslog/actions/runs/9147374885

packages: APT repo in R2

---

.github/workflows/upload-packages.yml

wnam is not in the bucket name, it was a user error by me.

github-actions: fix bucket name in upload-packages again

---

lib/cfg-lex.l
tests/light/functional_tests/filterx/test_filterx.py

From the awk docs:
https://www.gnu.org/software/gawk/manual/html_node/Escape-Sequences.html#index-mawk-utility
> Backslash Before Regular Characters
>
> If you place a backslash in a string constant before something
> that is not one of the characters previously listed, POSIX awk
> purposely leaves what happens as undefined.
>
> There are two choices:
>
> Strip the backslash out
> This is what BWK awk and gawk both do. For example, "a\qc"
> is the same as "aqc". (Because this is such an easy bug both
> to introduce and to miss, gawk warns you about it.) Consider
> ‘FS = "[ \t]+\|[ \t]+"’ to use vertical bars surrounded by
> whitespace as the field separator. There should be two
> backslashes in the string: ‘FS = "[ \t]+\\|[ \t]+"’.)
>
> Leave the backslash alone
> Some other awk …

cfg-lex: implement "Leave the backslash alone" for slash_string

---

docker/alpine.dockerfile

Upgrading alpine to 3.20 to [fix most of CVEs](https://github.com/axoflow/axosyslog/issues/186)

syslog-ng: update to alpine:3.20

---

modules/grpc/bigquery/bigquery-dest.cpp
modules/grpc/bigquery/bigquery-dest.h
modules/grpc/bigquery/bigquery-dest.hpp
modules/grpc/bigquery/bigquery-grammar.ym
modules/grpc/bigquery/bigquery-parser.c
modules/grpc/bigquery/bigquery-worker.cpp
modules/grpc/bigquery/bigquery-worker.hpp
modules/grpc/loki/loki-dest.cpp
modules/grpc/loki/loki-dest.h
modules/grpc/loki/loki-dest.hpp
modules/grpc/loki/loki-grammar.ym
modules/grpc/loki/loki-parser.c
modules/grpc/loki/loki-worker.cpp
modules/grpc/otel/otel-dest-worker.cpp
modules/grpc/otel/otel-dest-worker.hpp
modules/grpc/otel/otel-dest.cpp
modules/grpc/otel/otel-dest.h
modules/grpc/otel/otel-dest.hpp
modules/grpc/otel/otel-grammar.ym
modules/grpc/otel/otel-parser.c
news/feature-192.md

Example config:
```
opentelemetry(
...
headers(
"organization" => "Axoflow"
"stream-name" => "axo-stream"
)
);
```

otel,loki,bigquery: add `headers()` option to dest 

---

news/feature-178.md
scl/elasticsearch/elastic-datastream.conf
tests/copyright/policy

See https://www.elastic.co/guide/en/elasticsearch/reference/current/use-a-data-stream.html#add-documents-to-a-data-stream for details.
Sample trace log:
```
[2024-06-25T15:28:30.157427] cURL debug; worker='0', type='data_out', data='{"create":{ }}.{"PROGRAM":"prg00000","PRIORITY":"info","PID":"1234","MESSAGE":"seq: 0000000000, thread: 0000, runid: 1719322110, stamp: 2024-06-25T15:28:30 PADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADD","ISODATE":"2024-06-25T15:28:30+02:00","HOST":"localhost","FACILITY":"auth","@timestamp":"2024-06-25T15:28:30+02:00"}.'
[2024-06-25T15:28:30.157427] cURL debug; worker='0', type='ssl_data_in', data='.....'
[2024-06-25T15:28:30.157427] cURL debug; worker='0', type='ssl_data_in', …
```

scl: add elasticsearch-datastream destination

---

dbld/images/entrypoint.sh

Original issue:
- While going through the local dbld dev environment creation with:
- `dbld/rules image`
- `dbld/rules bootstrap`
- I've got the following error:
```
...
sudo: unknown user micek
sudo: error initializing audit plugin sudoers_audit
make: *** [dbld/rules:101: bootstrap-ubuntu-noble] Error 1
```
Root cause:
- After ubuntu:kinetic general "ubuntu" user was added to the base image with USER_ID: 1000
```
micek@DESKTOP-0E9OKG3:~$ docker run -it ubuntu:jammy bash -c "grep 1000 /etc/passwd"
micek@DESKTOP-0E9OKG3:~$ docker run -it ubuntu:kinetic bash -c "grep 1000 /etc/passwd"
micek@DESKTOP-0E9OKG3:~$ docker run -it ubuntu:lunar bash -c "grep 1000 /etc/passwd"
ubuntu:x:1000:1000:Ubuntu:/home/ubuntu:/bin/bash
micek@DESKTOP-0E9OKG3:~$ docker run -it ubuntu:mantic bash -c "grep 1000 …
```

[dbld] Handle already exist USER_ID in docker environment

---

lib/transport/tls-session.c
lib/transport/tls-session.h
lib/transport/transport-tls.c
news/feature-136.md

This resolves https://github.com/syslog-ng/syslog-ng/issues/4978

Add support for ssl peer fingerprint

---

lib/cfg-grammar.y
lib/filterx/CMakeLists.txt
lib/filterx/Makefile.am
lib/filterx/expr-compound.c
lib/filterx/expr-compound.h
lib/filterx/expr-condition.c
lib/filterx/expr-condition.h
lib/filterx/filterx-eval.c
lib/filterx/filterx-eval.h
lib/filterx/filterx-expr.c
lib/filterx/filterx-expr.h
lib/filterx/filterx-grammar.ym
lib/filterx/filterx-parser.c
lib/filterx/filterx-parser.h
lib/filterx/filterx-pipe.c
lib/filterx/filterx-pipe.h
lib/filterx/tests/CMakeLists.txt
lib/filterx/tests/Makefile.am
lib/filterx/tests/test_expr_compound.c
lib/filterx/tests/test_expr_condition.c
libtest/filterx-lib.c
tests/light/functional_tests/filterx/test_filterx.py

This merges various forms of expression lists into a single FilterXExpr instance:
* true and false branches of conditions
* top-level expression list of filterx blocks
* expression lists generated by our grammar (e.g. generator expressions)
It also implements expression tracing at all of these levels, so instead of only tracing top level statements, it also steps into the true/false branches of if statements.
It also fixes a few other issues:
* the requirement of having to add a "true" as the last statement in ifs to avoid dropping the entire message.
*

filterx: use a single compound expr to represent list of expressions

---

lib/filterx/expr-regexp.c
lib/filterx/expr-regexp.h
lib/filterx/filterx-globals.c
lib/filterx/tests/test_expr_regexp.c
tests/light/functional_tests/filterx/test_filterx.py

Complete implementation of regex_subst filterx function based on #195.
usage:
```
regexp_subst(string, pattern, replacement)
```
example:
```
filterx {
$MSG = regexp_subst($MSG, "u*", "X");
}
```

Filterx regexp subst

---

lib/filterx/expr-unset.c
lib/filterx/expr-unset.h
lib/filterx/filterx-globals.c
lib/filterx/filterx-grammar.ym
lib/filterx/filterx-parser.c
tests/light/functional_tests/filterx/test_filterx.py

Now we can do:
```
unset(foo, bar, baz);
```

filterx: make unset() a function and allow multiple args

---

modules/csvparser/filterx-func-format-csv.c

The delimiter is a single character and is not a null terminated string, so don't handle it as such.

csvparser: properly append the delimiter character to the resulting stirng in format_csv()

---

dbld/packages.manifest

I've noticed about this in syslog-ng/syslog-ng@9d0ac59aff75a298fdde09e655ba404c007f6da3.

dbld: do not hard-code Python minor version

---

lib/filterx/expr-plus.c
lib/filterx/filterx-object.c
lib/filterx/filterx-object.h
lib/filterx/object-datetime.c
lib/filterx/object-dict-interface.c
lib/filterx/object-list-interface.c
lib/filterx/object-primitive.c
lib/filterx/object-string.c
lib/filterx/tests/CMakeLists.txt
lib/filterx/tests/Makefile.am
lib/filterx/tests/test_expr_plus.c
lib/filterx/tests/test_object_datetime.c
lib/timeutils/unixtime.c
lib/timeutils/unixtime.h
tests/light/functional_tests/filterx/test_filterx.py

This pull request introduces a significant refactor as part of merging the Filterx lists and dictionaries. Specifically, it addresses the implementation of the + operator using the 'add' class method to ensure it behaves as expected.
Current Changes:
* redesign `expr-plus` operator
* extend every base class with `add` method
Future Work:
This is a partial solution; generators are not yet handled.
Part 2 will focus on integrating generator handling and refining generator grammar definitions.
example:
```
filterx {
$MSG = json();
$MSG.string = "foo" + "bar" + "baz";
$MSG.bytes = string(bytes("\xCA") + bytes("\xFE"));
$MSG.datetime_datetime = string(strptime("2000-01-01T00:00:00Z", "%Y-%m-%dT%H:%M:%S%z") + strptime("1970-01-01T02:00:00Z", "%Y-%m-%dT%H:%M:%S%z"));
$MSG.datetime_integer = …
```

FilterXObject class method add implementation for base types and list/dict variables #1

---

lib/filterx/filterx-grammar.ym
lib/logmatcher.c
lib/str-utils.h

```
real_lvalue:
: variable 
| expr '.' LL_IDENTIFIER 
| expr '[' expr ']' 
| expr '[' ']' 
```
Implementing semantics for this is a larger work, so I renamed the rules and added some comments to clarify this.
For example:
https://www.gnu.org/software/c-intro-and-ref/manual/html_node/Lvalues.html

filterx: refactor grammar to clarify what lvalue really is 

---

lib/cfg-block.c
lib/logreader.c
lib/plugin.c
lib/template/repr.c
modules/affile/affile-dest.c
news/bugfix-216.md

Patches are originally coming from syslog-ng/syslog-ng#4132 (@OverOrion do you want to close that PR?)
Fixes syslog-ng/syslog-ng#5025
Fixes syslog-ng/syslog-ng#5026
(Contains an alternative implementation of syslog-ng/syslog-ng#5032 and syslog-ng/syslog-ng#5031)

Null-pointer fixes

---

lib/filterx/CMakeLists.txt
lib/filterx/Makefile.am
lib/filterx/filterx-globals.c
lib/filterx/func-flatten.c
lib/filterx/func-flatten.h
lib/filterx/tests/CMakeLists.txt
lib/filterx/tests/Makefile.am
lib/filterx/tests/test_func_flatten.c
tests/light/functional_tests/filterx/test_filterx.py

Example:
```
dict = json({"top_level_field":42,"top_level_dict":{"inner_field":1337,"inner_dict":{"inner_inner_field":1}}});
flat_with_default_separator = dict;
flatten(flat_with_default_separator);
flat_with_custom_separator = dict;
flatten(flat_with_custom_separator, separator="->");
```

filterx: `flatten()`

---

cmake/Makefile.am
dbld/pkg-tarball
modules/afmongodb/Makefile.am

Patches were cherry-picked from syslog-ng/syslog-ng#5041 by @HofiOne.
(The PR also contains a fix for the VERSION file naming inconsistency that was worked around in the original PR.)

Tarball fixes

---

lib/filterx/CMakeLists.txt
lib/filterx/Makefile.am
lib/filterx/expr-generator.c
lib/filterx/expr-generator.h
lib/filterx/expr-plus-generator.c
lib/filterx/expr-plus-generator.h
lib/filterx/filterx-grammar.ym
lib/filterx/tests/CMakeLists.txt
lib/filterx/tests/Makefile.am
lib/filterx/tests/test_expr_plus_generator.c
tests/light/functional_tests/filterx/test_filterx.py

continue #217 with expr-plus-generator operator for handling mixed generator/variable operations
This commit continues the work from #217 by introducing the expr-plus-generator 
operator. This new operator is designed to handle plus operations over generators 
and mixed generator/variable operations, ensuring that both types of elements are 
processed seamlessly as a single generator.

Filterx expr plus operator for generators and += operator (part 2)

---

lib/cfg-grammar.y

cfg-lexer: fix KW_PLUS_ASSIGN preference

---

lib/filterx/filterx-expr.c
lib/filterx/filterx-expr.h
lib/filterx/filterx-object.c
lib/filterx/filterx-object.h

Thread boundaries were already crossed, for example:
FilterXGetAttr::attr and filterx_eval_push_error().
Even this can be considered as a bug, I saw other paths where we crossed
these boundaries.
We can always restore the non-atomic refcount if we see this as a
performance bottleneck in profiler results.

filterx: make ref_cnt atomic

---

lib/logproto/logproto-client.h
lib/logproto/logproto-proxied-text-server.c
lib/logproto/logproto-server.h
lib/logproto/tests/test-proxy-proto.c
lib/logreader.c
lib/logreader.h
lib/logwriter.c

The branch itself simplifies the LogProto handshake API and adds a unit test for the LogProtoAutoServer class (rfc6587)

Logproto remove handshake in progress

---

lib/msg-format.c
modules/syslogformat/syslog-format.c
modules/syslogformat/tests/test_syslog_format.c

This helps the "error" case match the successfully parsed ones. Also, this will improve consistency with linux:kmsg and linux:audit which are also possible values for $MSGFORMAT.

msg-format: include "syslog:" prefix for $MSGFORMAT values

---

modules/afsocket/tests/test-transport-mapper-inet.c
modules/afsocket/transport-mapper-inet.c

RFC3164 is both a data format and a transport. Sometimes 5424 style messages are received on a 3164-like transport, and seeing both 3164 in TRANSPORT and 5424 in MSGFORMAT can be a source of confusion.

afsocket: avoid using rfc3164 in $TRANSPORT

---

lib/logmsg/logmsg.c
lib/logmsg/logmsg.h
lib/logmsg/tests/test_log_message.c
lib/msg-format.c
lib/msg-format.h
lib/tests/test_msgparse.c
modules/syslogformat/syslog-format.c

**Problem:**
In case syslog-parser() fails, the entire log message is cleared: all name-value pairs, tags, along with partially parsed values already extracted from the message when the parsing failed. This also clears anything that was set prior to syslog-parser() and unrelated to syslog parsing (e.g. $SOURCEIP or $SOURCE or even $TRANSPORT). 
Then, syslog-ng adds some error information to the message and then attributes it to itself, as if it was coming from syslog-ng itself, but not via the internal() driver, rather by the driver which actually receives the message.
This behaviour makes sense in cases where the syslog parser is embedded in source drivers, as in that case the message should not have any other things yet.
It is not intuitive with syslog-parser() though, as in this case, …

Add no-piggyback-errors flag to syslog-parser() and syslog related source drivers.

---

lib/cfg-grammar-internal.c
lib/cfg-grammar-internal.h
lib/cfg-grammar.y
lib/filterx/filterx-metrics-labels.c
lib/filterx/filterx-metrics.c
lib/metrics/CMakeLists.txt
lib/metrics/Makefile.am
lib/metrics/dyn-metrics-cache.c
lib/metrics/dyn-metrics-cache.h
lib/metrics/dyn-metrics-store.c
lib/metrics/dyn-metrics-store.h
lib/metrics/dyn-metrics-template.c
lib/metrics/dyn-metrics-template.h
lib/metrics/metrics-template.c
lib/metrics/metrics-tls-cache.c
lib/metrics/metrics-tls-cache.h
lib/metrics/metrics.c
modules/diskq/diskq-global-metrics.c
modules/http/http-worker.c
modules/http/http-worker.h
modules/metrics-probe/metrics-probe-grammar.ym
modules/metrics-probe/metrics-probe.c
modules/metrics-probe/metrics-probe.h
modules/metrics-probe/tests/test_metrics_probe.c
news/bugfix-243.md
tests/copyright/policy

The TLS cache of `metrics-probe()` has been extended with a global cache in order not to make metrics orphaned whenever an ivykis worker stops (after 10 seconds of inactivity).
The global cache requires a lock, but it is only updated on thread shutdown. It is purged during reload.
Refactor overview:
- metrics-cache --> dyn-metrics-store
- metrics-tls-cache --> dyn-metrics-cache
I've also tried to decouple metrics-template from the cache functionality, but it would have had performance implications, so I only added a comment about the coupled functionality.

Fix disappearing `metrics-probe()` counters

---

modules/csvparser/filterx-func-parse-csv.c

Depends on #249
csvparser-filterx: do not traverse column list 3 times
- constructing list
- g_list_length()
- traversing list
This also fixes a possible bug where a name-value pair passed to `filterx_string_new()` may not have been null-terminated.

csvparser-filterx: do not traverse column list 3 times

---

lib/filterx/filterx-grammar.ym
tests/light/functional_tests/filterx/test_filterx.py

This is now valid, and results in `json` and `json_array`:
```
dict = {};
list = [];
```

filterx: implicit json cast for generator assignment

---

lib/filterx/expr-getattr.c
lib/filterx/expr-getattr.h
lib/filterx/expr-setattr.c
lib/filterx/expr-setattr.h
lib/filterx/expr-variable.c
lib/filterx/expr-variable.h
lib/filterx/filterx-config.c
lib/filterx/filterx-config.h
lib/filterx/filterx-grammar.ym
lib/filterx/filterx-scope.c
lib/filterx/object-string.c
lib/filterx/object-string.h
lib/filterx/tests/test_expr_compound.c
lib/filterx/tests/test_expr_condition.c
lib/filterx/tests/test_filterx_expr.c

This also fixes a test issue where variables with double $ signs were used.
Instead of polluting FilterX expressions with `GlobalConfig` (to freeze them locally), the same is done on the grammar level. This also makes testing easier but has the disadvantage of losing some C-level type-checking (I added `g_assert()` calls instead).

Filterx freeze more objects

---

lib/filterx/expr-plus.c
tests/light/functional_tests/filterx/test_filterx.py

The right hand side can be a `message_value`, as we only extract value from it in the add operator implementations, but the left hand side is special in a way that it is also used to find the correct add implementation based on its type, so we need a properly typed object there.

filterx: support message_value on the left hand side of +

---

lib/cfg-lexer.c

In case an error happens during glob(), glibc returns GLOB_NOMATCH while musl returns GLOB_ABORTED. Handle both properly.

cfg-lexer: fix handling of glob return values on musl

---

lib/filterx/expr-function.c
lib/filterx/expr-function.h
lib/filterx/filterx-expr.c
lib/filterx/filterx-expr.h
lib/filterx/filterx-metrics.c
lib/filterx/filterx-private.h
lib/filterx/tests/test_expr_condition.c
lib/filterx/tests/test_expr_function.c

2 race conditions have been fixed around `FilterXFunctionArgs`:
- `retrieved` field should not be changed during eval
- expression `ref()/unref()` calls should not be called during eval
Depends on #252

Fix race condition in FilterX simple funcs and perf improvements

---

lib/filterx/CMakeLists.txt
lib/filterx/Makefile.am
lib/filterx/filterx-globals.c
lib/filterx/func-sdata.c
lib/filterx/func-sdata.h
tests/light/functional_tests/filterx/test_filterx.py

```
@version: 4.8
@include "scl.conf"
log {
source { example-msg-generator(num(1)
template("[Originator@6876 sub=Vimsvc.ha-eventmgr opID=esxui-13c6-6b16 sid=5214bde6 user=root][anotherSDID@32473 iut=4 eventSource=Application eventID=1012]")
); };
parser{sdata-parser();};
filterx {
bar = has_sdata();
foo = is_sdata_from_enterprise("6876");
vars();
};
destination { file("/dev/stdout"); };
};
```
```
[2024-08-07T14:57:58.003231] Setting value; name='.SDATA.Originator@6876.sub', value='Vimsvc.ha-eventmgr', type='string', msg='0x59da85103170', rcptid='1872'
[2024-08-07T14:57:58.003231] Setting value; name='.SDATA.Originator@6876.opID', value='esxui-13c6-6b16', type='string', msg='0x59da85103170', rcptid='1872'
[2024-08-07T14:57:58.003231] Setting value; name='.SDATA.Originator@6876.sid', …
```

filterx: add SDATA helper functions

---

lib/filterx/object-json-array.c
tests/light/functional_tests/filterx/test_filterx.py

The `FilterXJsonArray`, which inherits from `FilterXList`, performed a redundant range check in the `get_subscript` method, leading to incorrect `NULL` results in certain cases due to a bug. Since this range check is already handled in the `FilterXList` abstraction, the unnecessary and faulty code block has been removed.
Additionally, some end-to-end tests for range checks have been added.

Fiterx json array fix - unwanted NULL results in get_subscript

---

lib/filterx/filterx-object.h
lib/filterx/object-json-array.c
lib/filterx/object-json-object.c
modules/grpc/otel/filterx/otel-field.cpp
modules/json/filterx-format-json.c

json_object_to_json_string_ext() writes/cached into the given JSON object, so it's not thread safe.

filterx: perf improvement and fix race condition in readonly FilterXJson::to_json_literal()

---

modules/grpc/otel/otel-protobuf-parser.cpp
modules/grpc/otel/otel-protobuf-parser.hpp

Cherry-picked from syslog-ng/syslog-ng#5084 (@HofiOne)

otel/ipv6: respect ipv6 compile switch

---

lib/filterx/CMakeLists.txt
lib/filterx/Makefile.am
lib/filterx/expr-compound.c
lib/filterx/expr-done.c
lib/filterx/expr-done.h
lib/filterx/expr-drop.c
lib/filterx/expr-drop.h
lib/filterx/filterx-error.c
lib/filterx/filterx-error.h
lib/filterx/filterx-eval.c
lib/filterx/filterx-eval.h
lib/filterx/filterx-grammar.ym
lib/filterx/filterx-parser.c
lib/filterx/filterx-pipe.c
tests/light/functional_tests/filterx/test_filterx.py

Example config
```
log {
source { example-msg-generator(num(1) template("bar")); };
source { example-msg-generator(num(1) template("foo")); };
filterx {
if ($MSG =~ '.*foo.*' ){
drop;
}
else {
done;
declare var_should_not_exist = json(); # This will be skipped
};
};
filterx {
vars();
};
destination { file("/dev/stdout"); };
};
```
Result
```
Setting value; name='MESSAGE', value='-- Generated message. --', type='string', msg='0x6500309ffa40', rcptid='28'
Setting value; name='MESSAGE', value='bar', type='string', msg='0x6500309ffa40', rcptid='28'
Incoming generated message; msg='bar'
>>>>>> Source side message processing begin; location='./etc/drop_msg.conf:5:12', msg='0x6500309ffa40', rcptid='28'
Setting value; name='HOST_FROM', value='orion-T14G3', type='string', msg='0x6500309ffa40', …
```

Filterx: add drop/done

---

lib/filterx/filterx-eval.c

filterx-eval: fix leak in filterx_format_eval_result()

---

lib/filterx/object-datetime.c

It is particularly useful when the otel log record does not have a timestamp set.
With this we can write expressions, like:
```
date_str = log.time_unix_nano ?
string(log.time_unix_nano) :
string(log.observed_time_unix_nano);
```

filterx: make 0 sec 0 usec datetime falsy

---

lib/filterx/filterx-grammar.ym
modules/csvparser/filterx-func-parse-csv.c

filterx: support `declare` with generators and fix UB in `parse_csv()`

---

lib/logmsg/logmsg.c
lib/logmsg/logmsg.h
lib/msg-format.c
modules/syslogformat/syslog-format.c
modules/syslogformat/tests/test_syslog_format.c

The only case we had a hard error in RFC3164 when the incoming data had an opening angle bracket ("<") without a closing one. Actually this does not happen very often, but our piggy-backed error handling is a lot less user friendly than setting the right error tags. So let's do that.

syslog-format: get rid off RFC3164 error case in favour of setting error

---

lib/filterx/filterx-grammar.ym

Unfortunately, the syntax of function call with a generator as its first param is reserved for the generator casted assignment. Sometime in the future we should fix this conflict fully, but for now supporting generators starting from the second param is a bit better than not supporting them at all.
(Will be useful for startswith(), endswith())

filterx: support passing generator to functions' not first param

---

.github/workflows/devshell.yml

Signed-off-by: Szilard Parrag <szilard.parrag@axoflow.com>

ci: add --enable-extra-warnings for autotools

---

lib/logsource.c

The value of `free_window` was not updated properly as the counter was deregistered in `deinit()`, but `AckTracker`s propagate acknowledgments even after the source is deinitialized.

logsource: fix free_window counters

---

lib/persist-state.c
lib/persist-state.h
modules/affile/file-reader.c
modules/affile/tests/test_wildcard_file_reader.c
modules/affile/wildcard-file-reader.c
modules/affile/wildcard-source.c
news/bugfix-291.md

Backward-compatible fix for syslog-ng/syslog-ng#5090

wildcard-file: fix persist-name uniqueness with user-supplied name and collision with regular file sources

---

modules/affile/wildcard-source.c
news/bugfix-293.md

Previously, `directory_monitors` were stopped and destroyed in the `free()` method of `WildcardSourceDriver`.
This can cause a crash because flow-controlled sources may retain references to their driver (through their ack tracker), and the last `unref()` call may be executed from a source thread (non-main thread).
Stopping directory monitors in the `deinit()` method fixes this issue, and it also fixes another issue where the driver would register a new superfluous monitor for the same directory each config revert.
Fixes syslog-ng/syslog-ng#5085 and the mentioned monitor reregistration issue

wildcard-file: fix crash when flow-controlled driver gets destroyed

---

lib/driver.c
lib/logqueue-fifo.c
lib/logqueue-fifo.h

I was investigating a log source hang, and it occurred to me in this context that it's time to part ways with the legacy force-suspend functionality.

logqueue-fifo: remove legacy flow-control+log-fifo-size() coupling

---

lib/filterx/filterx-grammar.ym
lib/logsource.c
lib/logthrdest/logthrdestdrv.c
lib/metrics/dyn-metrics-template.c
lib/pragma-grammar.ym
modules/appmodel/transformation.c
modules/metrics-probe/metrics-probe.c
modules/python-modules/syslogng/debuggercli/tests/test_langcompleter.py

Fixes the following memory leaks:
```
==95913== 20 bytes in 4 blocks are definitely lost in loss record 97 of 1,829
==95913==    at 0x4843808: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95913==    by 0x4C14589: strdup (strdup.c:42)
==95913==    by 0x48AABD5: cfg_lexer_lookup_keyword (cfg-lexer.c:257)
==95913==    by 0x48AAF28: cfg_lexer_map_word_to_token (cfg-lexer.c:302)
==95913==    by 0x48EA0B7: _cfg_lexer_lex (cfg-lex.l:352)
==95913==    by 0x48AC8C0: _invoke__cfg_lexer_lex (cfg-lexer.c:971)
==95913==    by 0x48ACAD1: cfg_lexer_lex_next_token (cfg-lexer.c:1015)
==95913==    by 0x48AD0AE: cfg_lexer_lex (cfg-lexer.c:1202)
==95913==    by 0x492727F: filterx_lex (filterx-parser.c:70)
==95913==    by 0x4941CC6: filterx_parse (filterx-grammar.c:3802)
==95913== …
```

Various memory leak fixes

---

modules/xml/CMakeLists.txt
modules/xml/Makefile.am
modules/xml/filterx-parse-windows-eventlog-xml.c
modules/xml/filterx-parse-windows-eventlog-xml.h
modules/xml/filterx-parse-xml.c
modules/xml/filterx-parse-xml.h
modules/xml/tests/CMakeLists.txt
modules/xml/tests/Makefile.am
modules/xml/tests/test_filterx_parse_windows_eventlog_xml.c
modules/xml/xml-plugin.c
tests/copyright/policy
tests/light/functional_tests/filterx/test_filterx.py

I tried to do this cleanly with minimal code duplication, and this is what I could achieve. I am still not completely satisfied with the result, but I don't see how could this be improved without making it less clean.

filterx: `parse_windows_eventlog_xml()`

---

lib/filterx/expr-unset.c
lib/filterx/filterx-expr.h

as the summary says, refuse the non-unsettable arguments during compilation.

filterx: unset(): refuse exprs that have no unset() method

---

tests/light/functional_tests/conftest.py
tests/light/functional_tests/filterx/test_filterx_update_metric.py
tests/light/src/syslog_ng/syslog_ng_cli.py

These minor fixes helps to run light more comfortable.
- fix 1: add fix for a deprecated API call (`psutil.Process().connections()`)
- fix 2: fix flaky testcase: test_filterx_update_metric_level()
- fix 3: handle syslog-ng crash when no core file has been detected

light: Add 3 minor fixes for a: deprecation warning, flaky testcase and crash detection

---

lib/filterx/object-primitive.c
lib/filterx/tests/test_object_double.c
lib/filterx/tests/test_object_integer.c

filterx: support casting datetime to integer or double

---

lib/filterx/CMakeLists.txt
lib/filterx/Makefile.am
lib/filterx/expr-literal-generator.c
lib/filterx/expr-literal-generator.h
lib/filterx/func-flags.h
lib/filterx/func-unset-empties.c
lib/filterx/func-unset-empties.h
lib/filterx/tests/test_func_unset_empties.c
tests/light/functional_tests/filterx/test_filterx.py

- Default empty set: "", null, [], {}.
- Optional named arguments:
- recursive: Enables recursive processing of nested dictionaries.
- ignorecase: Enables case-insensitive matching.
- replacement: Specifies a filterxobject to replace target elements instead of removing them.
- targets: A list of elements to identify for removal or replacement, clearing the default empty set.
- UTF-8 support.
- ignorecase and recursive args are defaults to TRUE
This change removes elements from the given dictionary or list that match
the empty set. If the recursive argument is provided, the function will
process nested dictionaries as well. The replacement argument allows
replacing target elements with a specified object, and the targets
argument customizes which elements are removed or replaced, …

filterx: rework of unset_empties

---

modules/affile/logproto-file-writer.c
news/bugfix-303.md

If a partial write occurs, the written messages must be acknowledged.
It is important to note that a message may be written partially.
In that case, the message will be acknowledged once the complete write is successful. If write errors occur during this process, the partially written message may be duplicated.

`file()`, `stdout()`: fix log sources getting stuck

---

dbld/rules

For example in CI, like GitHub Actions.

dbld: do not try to get pseudo terminal when TTY is not available

---

charts/axosyslog/Chart.yaml
charts/axosyslog/templates/collector-config.yaml
charts/axosyslog/templates/service.yaml
charts/axosyslog/templates/syslog-config.yaml
charts/axosyslog/values.yaml
modules/grpc/otel/otel-plugin.c

> Error parsing log statement: syntax error, unexpected LL_IDENTIFIER

otel: fix axosyslog-otlp() source/destination

---

tests/light/CMakeLists.txt

The make light-check command appends the EXTRA_ARGS environment variable to the command line arguments. Its primary purpose is to filter light tests during execution, but by not enforcing the -k argument, its use becomes more versatile.
example:
```make light-check EXTRA_ARGS="-k test_unset_empties"```

light test: add EXTRA_ARGS processing

---

lib/logthrsource/logthrsourcedrv.c
lib/logthrsource/logthrsourcedrv.h
modules/grpc/otel/otel-source.cpp
news/bugfix-310.md

`init_window_size` was always 0 when `workers()` was set to `>1`, because it was placed too early in the `init()` method: `-1 / num_workers `.

otel: fix multi-worker window and fetch-limit calculation

---

lib/filterx/func-unset-empties.c
tests/light/functional_tests/filterx/test_filterx.py

- pre-validation of utf8 input string on eval
- targets literal generator list parse-time utf8 validation

Filterx invalid utf8 fix for unset_empties

---

lib/cfg-lexer.c
lib/cfg-lexer.h
lib/cfg.c
news/bugfix-312.md

Template functions, for example, are constructed right when AxoSyslog parses the configuration, so the `@version` directive must be placed at the top of the config file to make it consistent.
This patch fixes the implicit "current version" mechanism (when no `@version` is specified) by moving it back to the lexer, and warns the user about misplaced or redefined `@version` directives.

cfg: fix config-version incosistencies

---

lib/filterx/filterx-eval.h
lib/logmpx.c
lib/logthrsource/logthrsourcedrv.c
lib/logthrsource/logthrsourcedrv.h
news/bugfix-314.md

logthrsource: fix sources getting stuck due to unclosed batches

---

modules/python-modules/syslogng/modules/s3/s3_destination.py

AxoSyslog leaks an amount of memory every time it's reloaded if an s3
destination is configured (#317). As a quick workaround we partially revert the
patch introducing the use of `boto3.Session` when no `role()` is set.

s3: workaround on-reload memleak when no role is set

---

lib/filterx/CMakeLists.txt
lib/filterx/Makefile.am
lib/filterx/filterx-globals.c
lib/filterx/func-str.c
lib/filterx/func-str.h
tests/light/functional_tests/filterx/test_filterx.py

Init time optimized version of https://github.com/axoflow/axosyslog/pull/277.
I opted for closing that because the changes are really different.

lib/filterx: add startswith / endswith / includes functions

---

dbld/builddeps
dbld/images/almalinux-8.dockerfile
dbld/images/almalinux-9.dockerfile
dbld/images/centos-7.dockerfile
dbld/images/debian-bookworm.dockerfile
dbld/images/debian-bullseye.dockerfile
dbld/images/debian-sid.dockerfile
dbld/images/debian-testing.dockerfile
dbld/images/fedora-39.dockerfile
dbld/images/fedora-40.dockerfile
dbld/images/ubuntu-focal.dockerfile
dbld/images/ubuntu-jammy.dockerfile
dbld/images/ubuntu-lunar.dockerfile
dbld/images/ubuntu-mantic.dockerfile
dbld/images/ubuntu-noble.dockerfile

To avoid out of date packages to break the image build
Cherry-picked from https://github.com/syslog-ng/syslog-ng/pull/5152 by @kovgeri01

 dbld: Update docker container before installing packages

---

lib/messages.h

So far if we were to use evt_tag_error() in debug or trace messages we got a compilation error. Fix that.

messages: capture errno in debug & trace messages as well

---

lib/filterx/expr-variable.c
lib/filterx/filterx-eval.h

- **lib/filterx: refactor _pull_variable_from_message**
- **lib/filterx: remove obsolete filterx_eval_sync_scope_and_message() function declaration**

Minor FilterX cleanups

---

modules/grpc/common/grpc-dest.hpp

`std::tolower` is not an addressible function, the intended way to use it is within a lambda.
See the following for more information:
https://devblogs.microsoft.com/oldnewthing/20241007-00/?p=110345
https://en.cppreference.com/w/cpp/string/byte/tolower

Fix std::transform and std::tolower usage in GRPCDest

---

dbld/rules

No command was passed to /dbld/shell in these cases, causing these shells to exit.

dbld/rules: fix login and root-login targets

---

lib/cfg-block-generator.c

```
@version: current
block destination second(...) {
`__VARARGS__`
};
block destination first(...) {
second(`__VARARGS__`);
};
log {
destination{ first(some-param("")) };
};
```
After the fix:
```
[2024-10-15T09:49:23.089776] Unknown argument, adding it to __VARARGS__; argument='some_param', value='', reference='../install_dir/etc/empty.conf:12:17'
[2024-10-15T09:49:23.089776] Unknown argument, adding it to __VARARGS__; argument='some_param', value='', reference='../install_dir/etc/empty.conf:8:7'
Error parsing log statement: syntax error, unexpected LL_IDENTIFIER, expecting '}'
In ../install_dir/etc/empty.conf:4:7-4:17:
-1      
0       #Start Block block destination second() at ../install_dir/etc/empty.conf:3
1       ## some_param=
2       @line "../install_dir/etc/empty.conf" 3 31
3 …
```

fix(lib): do not insert "nulls" as values for __VARARGS__ config arguments

---

lib/logthrdest/logthrdestdrv.c
modules/grpc/bigquery/bigquery-dest.cpp
modules/grpc/bigquery/bigquery-dest.h
modules/grpc/bigquery/bigquery-dest.hpp
modules/grpc/bigquery/bigquery-grammar.ym
modules/grpc/bigquery/bigquery-worker.cpp
modules/grpc/common/grpc-dest-worker.cpp
modules/grpc/common/grpc-dest-worker.hpp
modules/grpc/common/grpc-dest.cpp
modules/grpc/common/grpc-dest.h
modules/grpc/common/grpc-dest.hpp
modules/grpc/common/grpc-grammar.ym
modules/grpc/common/grpc-source.cpp
modules/grpc/common/metrics/grpc-metrics.cpp
modules/grpc/loki/loki-dest.cpp
modules/grpc/loki/loki-dest.h
modules/grpc/loki/loki-dest.hpp
modules/grpc/loki/loki-grammar.ym
modules/grpc/loki/loki-worker.cpp
modules/grpc/loki/loki-worker.hpp
modules/grpc/otel/otel-dest-worker.cpp
modules/grpc/otel/otel-dest-worker.hpp
modules/grpc/otel/otel-dest.cpp
modules/grpc/otel/otel-dest.hpp
news/feature-334.md

otel, loki: support dynamic `headers()`

---

modules/http/http.c

There are use-cases where the user wants to maintain ordering for certain categories of messages. In that case, closing the batch early is not necessary.
flush_on_worker_key_change can be changed from the HTTP destination's config, we should only force-set it to TRUE when templated URLs are used together with batches and multiple workers.

http: set flush_on_worker_key_change only when templateURL+batches are used

---

modules/grpc/bigquery/bigquery-dest.cpp
modules/grpc/bigquery/bigquery-dest.h
modules/grpc/bigquery/bigquery-dest.hpp
modules/grpc/bigquery/bigquery-grammar.ym
modules/grpc/bigquery/bigquery-parser.c
modules/grpc/bigquery/bigquery-worker.cpp
modules/grpc/bigquery/bigquery-worker.hpp
modules/grpc/common/CMakeLists.txt
modules/grpc/common/Makefile.am
modules/grpc/common/grpc-dest.cpp
modules/grpc/common/grpc-dest.h
modules/grpc/common/grpc-dest.hpp
modules/grpc/common/grpc-grammar.ym
modules/grpc/common/grpc-parser.h
modules/grpc/common/schema/CMakeLists.txt
modules/grpc/common/schema/Makefile.am
modules/grpc/common/schema/grpc-schema.cpp
modules/grpc/common/schema/grpc-schema.hpp
modules/grpc/loki/loki-grammar.ym
modules/grpc/otel/otel-grammar.ym

This will be useful for other drivers that want to support setting the message schema from config.
Depends on #334

grpc: factor out schema related functionality from bigquery to common

---

lib/driver.c
lib/filter/filter-pipe.c
lib/filterx/filterx-pipe.c
lib/filterx/filterx-scope.c
lib/filterx/filterx-scope.h
lib/logmsg/logmsg.c
lib/logpipe.h
lib/parser/parser-expr.c
lib/rewrite/rewrite-expr.c
modules/csvparser/tests/test_csvparser.c
modules/timestamp/tests/test_date.c
tests/light/functional_tests/filterx/test_filterx.py
tests/light/src/syslog_ng/syslog_ng_cli.py

This PR fixes accessing `LogMessage` type FilterX variables in case there had been changes between `filterx` blocks.

FilterX: fix invalid LogMessage variables access

---

packaging/package-indexer/indexer/deb_indexer.py

This reverts commit 5179c02070973be3822088500f6358f95cfcc73e.

Revert "package-indexer: temporarily dry-run old nightly removal"

---

lib/filterx/object-datetime.c
tests/light/functional_tests/filterx/test_filterx.py

add date heuristics of wallclocktime to strptime in filterx

---

tests/light/src/syslog_ng/syslog_ng_executor.py

This will cause gdb under light to use a larger font size so that's actually legible.

light: use larger fonts when executing xterm

---

lib/stats/stats-cluster.c
news/bugfix-370.md

AxoSyslog now has a lot of gauge metrics, which should not be reset. Instead of implementing metric typing support and filtering based on that, this patch disallows the reset mechanism for all new metrics, since resetting anything sent to Prometheus does not make sense.
(The patch keeps the original behavior for legacy stats counters.)

stats: do not allow resetting Prometheus metrics

---

lib/scanner/csv-scanner/csv-scanner.c
lib/scanner/csv-scanner/csv-scanner.h
modules/cef/event-format-parser-cfg.h
modules/cef/event-format-parser.c
modules/cef/event-format-parser.h
modules/cef/filterx-func-parse-cef.h
modules/cef/filterx-func-parse-leef.c
modules/cef/filterx-func-parse-leef.h
modules/cef/tests/CMakeLists.txt
modules/cef/tests/Makefile.am
modules/cef/tests/test-filterx-function-parse-cef.c
modules/cef/tests/test-filterx-function-parse-leef.c
modules/cef/tests/test_helpers.c
modules/cef/tests/test_helpers.h
tests/copyright/policy

This PR adds support for the LEEF 2.0 format, specifically focusing on its dynamic header field, `delimiter`. The task required a significant refactor of the event-parser base module and the unit test framework. Additionally, it introduces optional named arguments for the filterx function, allowing for forced overrides of `pair-separator` and `value-separator`. This enhancement will enable us to parse specific non-standard CEF/LEEF messages more effectively.
examples:
```
filterx {
dict = {};
dict.A = parse_cef($MSG, pair_separator="^", value_separator="#");
dict.B = parse_cef($MSG);
dict.C = parse_leef($MSG);
dict.D = parse_leef($MSG, pair_separator="|");
}

Filterx parse leef 2.0

---

CONTRIBUTING.md
DEVELOPMENT-GUIDE.md

Intends to do two things:
* Give new contributors a high level view of the source code and architecture.
* Document our agreed but not written coding conventions.

DEVELOPMENT-GUIDE: add Development Guide 

---

lib/debugger/debugger-main.c
lib/debugger/debugger-main.h
lib/debugger/debugger.c
lib/debugger/debugger.h
lib/debugger/tracer.c
lib/debugger/tracer.h
lib/mainloop-control.c
syslog-ng-ctl/commands/attach.c

This is a continuation of #326 to add interactive debugger functionality over syslog-ng-ctl

Syslog ng ctl attach debugger

---

lib/debugger/debugger.c
lib/debugger/tracer.c
lib/debugger/tracer.h
lib/mainloop.c

This is a continuation o #327 to add interrupt handling to the debugger. At the moment it only works on the original console, syslog-ng-ctl attach debugger does not propagate ctrl+c signals yet.

Debugger interrupt handling

---

lib/filterx/CMakeLists.txt
lib/filterx/Makefile.am
lib/filterx/filterx-globals.c
lib/filterx/filterx-metrics-labels.c
lib/filterx/filterx-metrics-labels.h
lib/filterx/filterx-metrics.c
lib/filterx/func-flatten.c
lib/filterx/object-metrics-labels.c
lib/filterx/object-metrics-labels.h
lib/filterx/tests/test_func_flatten.c
lib/filterx/tests/test_metrics_labels.c
lib/filterx/tests/test_object_filterx_metrics_labels.c
lib/stats/stats-prometheus.c
lib/stats/stats-prometheus.h
news/fx-feature-365.md
tests/light/functional_tests/filterx/test_filterx.py

filterx: `update_metrics()` and `flatten()` perf improvements

---

modules/grpc/otel/syslog-ng-otlp-dest-worker.cpp
news/bugfix-384.md

Missing from:
885051d331f9ce52a1ac90dfd8e4f28f0d741f73

grpc/otel: add missing client context creation to axosyslog-otlp()

---

.github/workflows/macos.yml
contrib/Brewfile

pkgconf is a newer, actively maintained implementation of pkg-config.
This is to fix CI on certain macOS runner instances (not all of them are affected). pkg-config is now migrated to pkgconf in brew, but a few runners have old pkg-config installed in a way they can't be overwritten by just a simple upgrade.

ci: fix macOS dep conflict

---

lib/filterx/filterx-globals.c
lib/filterx/func-vars.c
lib/filterx/func-vars.h
news/fx-feature-393-1.md
news/fx-feature-393-2.md
tests/light/functional_tests/filterx/test_filterx.py

Inverse of `vars()`.
Note: FilterX level variables are loaded and `declare`d.

filterx: `load_vars()`

---

.github/workflows/axosyslog-docker.yml

https://github.blog/news-insights/product-news/arm64-on-github-actions-powering-faster-more-efficient-build-systems/
> We expect to begin offering Arm runners for open source projects by the end of the year. 
Unfortunately, I can't test this in my fork.

ci: build arm64 image natively without QEMU

---

lib/filterx/expr-boolalg.c
lib/filterx/expr-comparison.c
lib/filterx/expr-condition.c
lib/filterx/expr-condition.h
lib/filterx/expr-null-coalesce.c
lib/filterx/expr-plus.c
lib/filterx/filterx-grammar.ym
lib/filterx/object-primitive.h

Can be useful when FilterX code is extracted into SCL blocks with parameters, or when the configuration is generated.
For example:
```
optimized_away_to_literal = `from_scl` && !`from_scl2` ? (`from_scl3`) ?? "ok" : "not " + "ok"
```
Depends on #387 (CI)

FilterX operator optimization for literals

---

lib/filterx/expr-assign.c
lib/filterx/expr-boolalg.c
lib/filterx/expr-comparison.c
lib/filterx/expr-compound.c
lib/filterx/expr-condition.c
lib/filterx/expr-function.c
lib/filterx/expr-function.h
lib/filterx/expr-get-subscript.c
lib/filterx/expr-getattr.c
lib/filterx/expr-isset.c
lib/filterx/expr-null-coalesce.c
lib/filterx/expr-plus.c
lib/filterx/expr-set-subscript.c
lib/filterx/expr-setattr.c
lib/filterx/expr-template.c
lib/filterx/expr-variable.c
lib/filterx/filterx-expr.c
lib/filterx/filterx-expr.h
news/fx-feature-398.md

FilterX expression eval metrics

---

lib/filterx/CMakeLists.txt
lib/filterx/Makefile.am
lib/filterx/expr-literal-generator.c
lib/filterx/filterx-globals.c
lib/filterx/func-set-fields.c
lib/filterx/func-set-fields.h
news/fx-feature-397.md
tests/light/functional_tests/filterx/test_filterx.py

A recurring pattern in FilterX is to take a dict and set multiple fields in it with overrides or defaults.
`set_fields()` takes a dict as the first argument and `overrides` and `defaults` as optional parameters.
`overrides` and `defaults` are also dicts, where the key is the field's name, and the value is either an expression, or
a list of expressions. If a list is provided, each expression will be evaluated, and the first successful, non-`null` one will
be used to set the respective field's value. This is similar to chaining null-coalescing (`??`) operators, but is more performant.
`overrides` are always processed for each field. The `defaults` for a field are only processed, if the field does not already have a value set.
Example usage:
```
set_fields(
my_dict,
overrides={
"foo": …
```

filterx: `set_fields()`

---

modules/http/http.c

In case only batch-bytes() is set, the logthrdestdrv core will flush the batch, as it
will deduce that no batching is needed. Fix that.
PS: we might need a similar fix in gRPC related drivers.

http: fix batch-lines() in case only batch-bytes() is set

---

modules/grpc/common/grpc-dest.cpp

grpc: fix batch-lines() in case only batch-bytes() is set

---

lib/filterx/expr-regexp.c
lib/filterx/expr-regexp.h
lib/filterx/tests/test_expr_regexp.c
tests/light/functional_tests/filterx/test_filterx.py

Enhanced regexp_subst to support match group identifiers in patterns.
Since this feature could have a significant impact on performance, it is
controlled by a flag called 'groups', which is set to false by default.
To enable this feature, add the optional groups=true argument to your regexp_subst call.
example:
```
filterx{
$MSG.on = regexp_subst("25-02-2022", /(\d{2})-(\d{2})-(\d{4})/, "\\3/\\2/\\1", groups=true);
}
```
This feature could have been implemented using the pcre2_substitute() function provided by the PCRE2 library. However, this approach was not viable because pcre2_substitute() does not support zero-length matches, which are a critical aspect of syslog-ng's legacy regex matcher.
As a result, the implementation introduced unwanted/unnecessary code and increased complexity. …

Filterx regexp_subst supports match groups

---

lib/filterx/expr-regexp.c
lib/filterx/expr-regexp.h
lib/filterx/func-flags.h
lib/filterx/tests/test_expr_regexp.c
tests/light/functional_tests/filterx/test_filterx.py

continuation of #394 
based on https://github.com/axoflow/axosyslog/issues/392
Introduced two new optional flags: keep_zero and list_mode.
The result type no longer switches between dict and list based on the presence of named groups.
The default result type is now dict.
list_mode can force a list result, either via the flag or the type of the fillable (the fillable's type takes precedence).
Match group zero is now excluded by default unless no other groups are present. This behavior can be overridden using the keep_zero flag.
Additionally, the FilterXRematchState structure, shared across other regexp functions, has been updated with a generic flags field. This allows functions to pass custom options to the state without incurring additional overhead.

Filterx regexp_search rework

---

modules/python-modules/syslogng/modules/s3/s3_destination.py
modules/python-modules/syslogng/modules/s3/s3_object.py
modules/python-modules/syslogng/modules/s3/scl/s3.conf
news/feature-408.md

S3 dest: `content-type()`

---

news/fx-feature-399.md

News regexp search

---

lib/logproto/logproto-buffered-server.h
lib/logproto/logproto-text-server.c
lib/logreader.c
lib/logreader.h
modules/affile/file-reader.c
modules/affile/poll-file-changes.c

This is an alternative solution to #388 
* this fixes a regression caused by #155 , reported by @HofiOne  
* This simplifies the I/O tracking for files, LogProto/LogTransport should get full authority on whether data is already available before poll and also how we need to poll it
* Instead of the ugly "immediate_check" mechanism, we wake up LogReader if there's any event available
The regression happens in the LogReader: #155 causes us to skip a poll iteration because of the handshake (even if it does not exist). This causes a problem as at the very first iteration it is only "immediate_check" that causes us to start fetching messages. And that only fires once. By skipping that first iteration, we stall and stop fetching messages.
Instead of reverting the handshake related change  (which …

Fix handshake regression

---

lib/filterx/expr-regexp-subst.c
lib/filterx/tests/test_expr_regexp_subst.c
tests/light/functional_tests/filterx/test_filterx.py

continuation of #405
- substitution match groups feature is enabled by default
- the match group control flag argument `groups` inverted and renamed to `nogroups`
- match group indexes are now supported up to 999 instead of 9 (multi digits)
- checking replacement pattern at construct time to disable match group feature if it's unnecessary

Filterx regexp_subst match group changes

---

news/fx-feature-409.md

News regexp subst

---

lib/transport/transport-stack.c
lib/transport/transport-tls.c
news/bugfix-420.md

`log_transport_free()` is responsible for shutdown, which requires an open fd.

transport-stack: fix shutdown

---

modules/http/http-worker.c
modules/http/http-worker.h

This patch adds the response text returned by the HTTP server to various diagnostic messages, so issues with the server can be diagnosed more easily.
```
@version: current
options { keep-hostname(yes); };
log {
source { tcp(port(2000)); };
destination {
http(
#url("https://httpbin.org/status/502")
url("https://httpbin.org/html")
content-compression(gzip)
workers(1)
tls(
ssl_version(tlsv1_2)
peer-verify(no)
)
time-reopen(1)
body("$DATE $HOST $MSGHDR$MSG")
batch-bytes(10MiB)
batch-timeout(1000)
retries(3)
); 
};
};
```

http: add HTTP response text to the diagnostic messages

---

lib/filterx/CMakeLists.txt
lib/filterx/Makefile.am
lib/filterx/filterx-globals.c
lib/filterx/func-keys.c
lib/filterx/func-keys.h
lib/filterx/object-dict-interface.c
lib/filterx/object-dict-interface.h
lib/filterx/tests/CMakeLists.txt
lib/filterx/tests/Makefile.am
lib/filterx/tests/test_func_keys.c
lib/filterx/tests/test_object_dict_interface.c
tests/light/functional_tests/filterx/test_filterx.py

example:
```
d = {"foo":1,"bar":[3,2,1],"baz":{"tik":"tak"}};
$MSG.keys = keys(d); #["foo","bar","baz"]
$MSG.elt = keys(d)[0]; #"foo"
```

filterx keys function

---

lib/filterx/expr-compound.c

This is a performance optimization that should eliminate filter_object_repr() calls from the profile.

filterx/expr-compound: don't format result of expression unless debug is enabled

---

lib/cfg-source.c

This is not an exploitable problem, as the index that can overflow cannot be controlled externally. It will cause a segfault if there's a location tracking issue or if the source location we are extracting the source text from is incorrect.

cfg-source: avoid indexing over the end of the lines array

---

lib/filterx/func-unset-empties.c

We incorrectly called filterx_expr_init_method() directly instead of going through the virtual function pointer.

filterx/unset-empties: call the virtual init function of object_expr

---

lib/filterx/filterx-scope.c
lib/filterx/filterx-variable.c
lib/filterx/filterx-variable.h

Optimize the removal of multiple elements.

filterx/filterx-scope: don't move the variables array multiple times

---

lib/logpipe.c

This patch refactors log_pipe_queue() to allow tail-call-optimization, meaning gcc uses a jmp to "call" the next queue method instead of a call, thereby eliminating the stack frame of log_pipe_queue().
This means that stacktraces are shorter when measuring them with perf and may also improve a bit of performance, although it was 2-3% in my measurements, which could easily be attributed to jitter.

logpipe: allow log_pipe_queue() to be tail-call-optimized

---

lib/filterx/expr-boolalg.c
lib/filterx/expr-comparison.c
lib/filterx/expr-compound.c
lib/filterx/expr-condition.c
lib/filterx/expr-condition.h
lib/filterx/expr-function.c
lib/filterx/expr-function.h
lib/filterx/expr-generator.c
lib/filterx/expr-generator.h
lib/filterx/expr-get-subscript.c
lib/filterx/expr-getattr.c
lib/filterx/expr-literal-generator.c
lib/filterx/expr-plus-generator.c
lib/filterx/expr-plus.c
lib/filterx/expr-regexp-search.c
lib/filterx/expr-regexp-subst.c
lib/filterx/expr-regexp.c
lib/filterx/expr-set-subscript.c
lib/filterx/expr-setattr.c
lib/filterx/expr-unset.c
lib/filterx/filterx-expr.c
lib/filterx/filterx-expr.h
lib/filterx/filterx-grammar.ym
lib/filterx/filterx-pipe.c

This branch moves the various constructor-time optimizations into a separate method, which has a few advantages:
1) it is more readable
2) it becomes optional
3) memory management is simplified
4) distinct optimizations steps can cascade to higher level expressions (e.g. a comparison between literals can be promoted into a literal which can then allow optimization for a conditonal as well)

Filterx introduce optimize method

---

lib/filterx/expr-condition.c
lib/filterx/expr-function.c
lib/filterx/expr-function.h
lib/filterx/expr-null-coalesce.c
lib/filterx/filterx-metrics-labels.c
lib/filterx/filterx-metrics-labels.h
lib/filterx/filterx-metrics.c
lib/filterx/filterx-metrics.h
lib/filterx/func-flatten.c
lib/filterx/func-istype.c
lib/filterx/func-keys.c
lib/filterx/func-set-fields.c
lib/filterx/func-str.c
lib/filterx/func-unset-empties.c
lib/filterx/object-datetime.c
lib/filterx/tests/test_metrics_labels.c
modules/cef/event-format-parser.c
modules/csvparser/filterx-func-format-csv.c
modules/csvparser/filterx-func-parse-csv.c
modules/kvformat/filterx-func-format-kv.c
modules/kvformat/filterx-func-parse-kv.c
modules/metrics-probe/filterx/func-update-metric.c
modules/xml/filterx-parse-xml.c

filterx: optimize followup

---

dbld/images/devshell.dockerfile
dbld/packages.manifest
dbld/rules

Ubuntu has -fno-omit-frame-pointer in CFLAGS which Debian testing does not have, making profiling a lot more difficult on Debian.
At least as long as https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=767756 is not resolved, we are better off on Ubuntu as a devshell.
Note that this patch separates the tarball image (which continues to remain Debian testing) and devshell.

dbld: change devshell to use ubuntu-noble as base

---

lib/filterx/object-message-value.c

Macro based values are captured into an allocated buffer in FilterXMessageValue, but there was no extra NUL character added in case repr_len was specified (which is for any log_msg_get_value() resolutions).
This causes valgrind to throw errors when the APPEND_ZERO() macro is used.

filterx/object-message-value: ensure that an extra NUL character is present

---

lib/filterx/filterx-grammar.ym

This adds location information for non-statement expressions, which means we would see less of those "n/a" locations.

Filterx location tracking for all exprs

---

lib/logmsg/logmsg.c
lib/logmsg/logmsg.h

In my effort to create a generation counter for the LogMessage (to indicate change), I was looking for an empty slot in the struct. While doing so, I documented the members and redid the layout of the struct to ensure that the most often changed fields all fit into the first cacheline.
I also noticed, that in case of cloning, we first zero initialized the struct and then overwritten its content using
memcpy, which I have removed in this PR.

Avoid excess memset() plus make room for a generation counter

---

lib/filterx/expr-variable.c
lib/filterx/filterx-variable.h
lib/filterx/object-message-value.c
lib/logmsg/logmsg.c
lib/logmsg/logmsg.h
lib/template/compiler.c
lib/template/eval.c
lib/template/globals.c
lib/template/globals.h
lib/template/macros.c
lib/template/macros.h
lib/template/templates.c
lib/template/tests/test_template_compile.c
lib/value-pairs/value-pairs.c
tests/light/functional_tests/filterx/test_filterx.py

This PR ended a bit more than what the title says:
* the original goal was to check whether a variable is a hard macro and do this in the compilation phase, instead of during evaluation
* then I removed the macro wrapper for $MSG, which was not really doing much anymore
* this broke value-pairs
* also broke light tests, which relied on $MSG being a string, even though it was set to a protobuf/bytes value
* and I also noticed an read-side off-by-one for macro based variables
* I ended up also adding a warning when using bytes or protobuf values in a template which does not render without a type hint.
With all that fixed is what we have in this branch.

Filterx: check if value is a macro during compilation

---

lib/filterx/expr-compound.c
lib/filterx/expr-condition.c
lib/filterx/expr-done.c
lib/filterx/expr-drop.c
lib/filterx/expr-function.c
lib/filterx/expr-generator.c
lib/filterx/expr-get-subscript.c
lib/filterx/expr-getattr.c
lib/filterx/expr-literal-generator.c
lib/filterx/expr-literal.c
lib/filterx/expr-regexp.c
lib/filterx/expr-set-subscript.c
lib/filterx/expr-setattr.c
lib/filterx/expr-template.c
lib/filterx/expr-variable.c
lib/filterx/filterx-expr.c
lib/filterx/filterx-expr.h
libtest/filterx-lib.c

I extracted this patch from #423 so that we can build changes that build on this specific patch and can be merged independently of #423.
The point of this patch is to add a new "type" member into FilterXExpr, a string that can be used in various log messages.
I used this to initialize metrics in #423 but I might need it for identifying expr types instead of the "eval" function pointer in #433. Other than that I have a few other patches that change the expr constructors and simply started depending on this change as a part of their diff context.

filterx: use "type" as a description to FilterXExpr type

---

modules/systemd-journal/journal-reader.c

```
.../modules/systemd-journal/journal-reader.c: In function '_get_value_from_message.constprop.isra':
.../modules/systemd-journal/journal-reader.c:218:7: warning: '__builtin___strncpy_chk' output truncated before terminating nul copying as many bytes from a string as its length [-Wstringop-truncation]
218 |       strncpy(buf + cont, key, key_len);
|       ^
In function '_format_value_name_with_prefix',
inlined from '_get_value_from_message.constprop.isra' at /source/modules/systemd-journal/journal-reader.c:243:3:
.../modules/systemd-journal/journal-reader.c:211:15: note: length computed here
211 |     key_len = strlen(key);
|               ^~~~~~~~~~~
```   
This wasn't an actual issue as we were explicitly terminating the string with NUL in this case, so missing the NUL character was …

systemd-journal: fix spurious warning about about incorrect size passed to strncpy()

---

lib/filterx/expr-compound.c
lib/filterx/expr-condition.c
lib/filterx/expr-function.c
lib/filterx/expr-get-subscript.c
lib/filterx/expr-getattr.c
lib/filterx/expr-set-subscript.c
lib/filterx/expr-setattr.c
lib/filterx/expr-template.c
lib/filterx/expr-variable.c
lib/filterx/filterx-expr.c
lib/filterx/filterx-expr.h

This simplifies the registration of filterx eval metrics and at the same time makes them more granular.  
Please merge #444 first as I've extracted the initial patch from this series into a separate PR to facilitate merging other bits.

Filterx refactor eval metrics

---

lib/filterx/func-unset-empties.c
news/fx-feature-452.md
tests/light/functional_tests/filterx/test_filterx.py

UTF8 aware case folding are expensive, remove that feature for now. The branch also changes the default for the ignorecase parameter.

Filterx: unset-empties() performance changes

---

lib/filterx/func-str-transform.c
lib/filterx/func-str.c
lib/filterx/object-string.c
lib/filterx/object-string.h
lib/filterx/tests/test_object_string.c
lib/str-utils.h
modules/syslogformat/syslog-format.c
tests/copyright/policy
tests/light/functional_tests/filterx/test_filterx_funcs.py

This removes another set of allocations in upper/lower/includes/startswith/endswith
these are often used in initial qualification of the data, so their performance is important.

Filterx string performance opt

---

dbld/rules

This is only needed for gdb sessions, but it interferes with auth modules
in sudo, for example.
The issue will be still reproducible in `dbld shell-*`, let's investigate it separately.

Fix rpm build

---

lib/filterx/filterx-expr.c
lib/filterx/filterx-grammar.ym
lib/filterx/filterx-ref.c
lib/filterx/filterx-ref.h

These are three basically independent patches, but I didn't want to open a separate PR for all of these. Let's try these in one go. Should be relatively straightforward to review.

Filterx small changes

---

modules/cloud-auth/CMakeLists.txt
modules/cloud-auth/Makefile.am
modules/cloud-auth/azure-auth.cpp
modules/cloud-auth/azure-auth.h
modules/cloud-auth/azure-auth.hpp
modules/cloud-auth/cloud-auth-grammar.ym
modules/cloud-auth/cloud-auth-parser.c
news/feature-457.md
scl/CMakeLists.txt
scl/Makefile.am
scl/azure/azure-monitor.conf
tests/copyright/policy

Example usage:
```
azure-monitor-custom(table-name("table")
dcr-id("dcr id")
dce-uri("dce uri")
auth(tenant-id("tenant id")
app-id("app id")
app-secret("app secret")))))
```

Azure sentinel destination

---

lib/logmsg/logmsg.c
lib/logmsg/logmsg.h

This adds a counter to LogMessage to track changes made to the NVTable. Any set_value() would increment that counter. Any other fields (timestamps, etc) are not yet tracked, but probably should....

logmsg: add generation counter

---

lib/filterx/expr-template.c
lib/filterx/expr-variable.c
lib/filterx/filterx-eval.c
lib/filterx/filterx-eval.h
lib/filterx/filterx-pipe.c
lib/filterx/filterx-scope.c
lib/filterx/filterx-scope.h
lib/filterx/filterx-variable.c
lib/filterx/filterx-variable.h
lib/filterx/func-sdata.c
lib/filterx/func-vars.c
libtest/filterx-lib.c
tests/light/functional_tests/filterx/test_filterx_scope.py

This branch improves "changed" detection of variables, by not considering variables to be changed if all we do is unmarshal them.
It comes with a set of preparatory steps/refactors. Some of these can be considered unrelated, but I didn't want to open PRs separately.

Filterx unmarshal does not cause variables to be dirty

---

.github/workflows/macos.yml

fix: remove unrecognized brew flag `--preinstall` from osx build workflow

fix osx build

---

lib/filterx/expr-assign.c
lib/filterx/expr-comparison.c
lib/filterx/expr-compound.c
lib/filterx/expr-condition.c
lib/filterx/expr-done.c
lib/filterx/expr-drop.c
lib/filterx/expr-generator.c
lib/filterx/expr-get-subscript.c
lib/filterx/expr-getattr.c
lib/filterx/expr-isset.c
lib/filterx/expr-literal.c
lib/filterx/expr-null-coalesce.c
lib/filterx/expr-plus.c
lib/filterx/expr-set-subscript.c
lib/filterx/expr-setattr.c
lib/filterx/expr-template.c
lib/filterx/expr-unset.c
lib/filterx/expr-variable.c
lib/filterx/func-flatten.c
lib/filterx/func-istype.c
lib/filterx/func-sdata.c
lib/filterx/func-set-fields.c
lib/filterx/func-unset-empties.c

Next out of #434, this time it is based on #444 that needs to go in first.
There are two patches here (on top of #444):
* the nullv style constructors are reimplemented as a "delta" to the normal constructor to avoid code duplication
* _eval() methods are renamed everywhere so it's easier to read perf stackdumps

Filterx expr constructor improvements

---

modules/http/http.c
news/bugfix-464.md

When the URL is templated and batching is enabled it does not matter how many workers we have, we
need to close the batch when the partition key changes.
The condition for the if statement was wrong for a long time, however since 70c704c037 it not only resulted in a missing error log and missing init fail, but we ran with `flush-on-worker-key-change(no)`, messing up the batching.

http: enable flush-on-worker-key-change for 1 worker

---

lib/filterx/filterx-scope.c

Preallocate the right number of variables so that we never have to extend the variables array during runtime.

filterx/filterx-scope: keep track of the maximum number of variables

---

lib/filterx/func-str.c
tests/light/functional_tests/filterx/test_filterx.py
tests/light/functional_tests/filterx/test_filterx_funcs.py

This improves test coverage for startswith/endswith/includes as well as includes their performance by:
* not using dynamically allocated GString and GPtrArray instances
* using the glibc provided strstr() call instead of the one in glib

Filterx func str performance improvements

---

lib/filterx/expr-comparison.c
lib/filterx/object-datetime.c
lib/filterx/tests/test_expr_comparison.c
lib/filterx/tests/test_expr_plus.c
lib/filterx/tests/test_object_datetime.c
lib/timeutils/misc.h
lib/timeutils/unixtime.c
lib/timeutils/unixtime.h
lib/timeutils/wallclocktime.c
lib/timeutils/wallclocktime.h
modules/grpc/otel/filterx/otel-field.cpp
modules/grpc/otel/filterx/protobuf-field.cpp
modules/grpc/otel/tests/test-otel-filterx.cpp
tests/light/functional_tests/filterx/test_filterx.py

A bunch of datetime releated fixes:
- dump functions for wallclock time and unixtime (they were extermely useful, so i kept them)
- fix: filterx datetime string formatting error: unnecessary dash removed
- prepartion for nano second precision support: timeutils/misc extended, typo fixed
- fix:  unix_time_to_unix_epoch calculation
- fix: otel nanosecond-precision fields setter/getter
- unit test for otel nanosec precision and timezone information

Time releated fixes

---

lib/filterx/func-unset-empties.c

Every g_list_append() is an extra allocation, so by avoiding GList altogether we can reduce the number of malloc() calls by the number of keys that we unset.

filterx/unset-empties: avoid using a GList for keys to unset

---

modules/cloud-auth/azure-auth.hpp
modules/cloud-auth/google-auth.hpp

There is a macro that modifies the number parsing behavior of picojson (PICOJSON_USE_INT64).
When jwt-cpp/jwt.h includes picojson.h it explicitly enables PICOJSON_USE_INT64. I did not check the code thoroughly, but it is possible that they explicitly build on some int64_t related functionality.
However if we directly include jwt.h without setting PICOJSON_USE_INT64, picojson will not have int64_t support. This resulted in a strange behavior of having int64_t type hinted value in a json object, but the type checker not recognizing it as a number.

cloud-auth: do no directly include picojson/picojson.h

---

lib/filterx/expr-generator.c
lib/filterx/expr-generator.h
lib/filterx/expr-get-subscript.c
lib/filterx/expr-get-subscript.h
lib/filterx/expr-getattr.c
lib/filterx/expr-getattr.h
lib/filterx/expr-literal-generator.c
lib/filterx/expr-literal-generator.h
lib/filterx/expr-literal.c
lib/filterx/expr-literal.h
lib/filterx/expr-variable.c
lib/filterx/expr-variable.h
lib/filterx/filterx-expr.h

The current convention is to decide whether we are looking at a specific FilterXExpr instance based on the value of the
"eval" function pointer.
Issue is that #433 will change that pointer at runtime to incorporate expr level visibility into perf backtraces.
This could also be the beginning of a real FilterXExprType struct (to avoid repeating the function pointers into all expr instances), but this PR does not go that far.
NOTE: this does not create FILTERX_EXPR_TYPE_DECLARE() for all exprs, only those which had a filterx_expr_is_XXX() function. As long as noone is checking if an expr is of a specific type, this is optional.

Filterx expr type macros

---

lib/filterx/expr-variable.c
lib/filterx/filterx-eval.c
lib/filterx/filterx-pipe.c
lib/filterx/filterx-scope.c
lib/filterx/filterx-scope.h
lib/filterx/filterx-variable.c
lib/filterx/filterx-variable.h
lib/filterx/func-vars.c
lib/filterx/tests/test_filterx_expr.c
lib/logmsg/logmsg.c
lib/logmsg/logmsg.h
tests/light/functional_tests/filterx/test_filterx_scope.py

This pull request replaces the old "log_msg_has_changes" mechanism with the recently merged generation counter.
This has the following goals/benefits:
* it fixes a bug in message tracking, as previously we considered a message changed when it was cloned. But a message can change without being cloned.
* we delegate the message change tracking to FilterXScope, 
* this requires that FilterXScope now has a reference to the message being processed. 
* this becomes similar to what we do with "undeclared" floating variables
* the scope will provide a higher level interface to manage variables, moving the complexity from FilterXVariable to FilterXScope
* it adds slight changes and makes a couple of functions inline.
*

Filterx scope to track message changes

---

lib/str-utils.h

gchar is either signed or unsigned (127 may be the max value), guchar can be ASCII-checked, but then the 0-check is not needed.

str-utils: fix always true condition warning (-Wtype-limits)

---

.github/workflows/axosyslog-nightly.yml

From now on, we keep the last 30 nightlies, but we only build nightly packages and images if we have new changes on main. Manually triggering the job will always allow rebuilds.
This will avoid a unnecessary storage and computation costs and also increases the nightly retention period.

ci: schedule nightly only when there are new changes on main

---

packaging/package-indexer/remote_storage_synchronizer/s3_bucket_synchronizer.py

boto3 v1.36.0 introduced a new default integrity check for S3 operations. This breaks R2's S3 compatibility API, as it does not support integrity checks.
See https://github.com/boto/boto3/issues/4392
Hopefully fixes the nightly package indexing CI job.

package-indexer: disable R2 default integrity check

---

modules/grpc/otel/filterx/CMakeLists.txt
modules/grpc/otel/filterx/Makefile.am
modules/grpc/otel/filterx/object-otel-array.cpp
modules/grpc/otel/filterx/object-otel-array.hpp
modules/grpc/otel/filterx/object-otel-base.cpp
modules/grpc/otel/filterx/object-otel-base.hpp
modules/grpc/otel/filterx/object-otel-kvlist.cpp
modules/grpc/otel/filterx/object-otel-kvlist.hpp
modules/grpc/otel/filterx/object-otel-logrecord.cpp
modules/grpc/otel/filterx/object-otel-logrecord.hpp
modules/grpc/otel/filterx/object-otel-resource.cpp
modules/grpc/otel/filterx/object-otel-resource.hpp
modules/grpc/otel/filterx/object-otel-scope.cpp
modules/grpc/otel/filterx/object-otel-scope.hpp
tests/light/functional_tests/filterx/test_filterx.py

Axorouter encountered an error:
filterx: unable to repr; from='otel_kvlist', to='string'.
Upon investigating the issue, I found relevant hints in Axorouter’s configuration. The configuration suggests that OTel objects still require a repr method, but currently, a JSON-based workaround is used:
```
filterx {
log.body = string(log.body) ?? format_json(log.body);
```
To address this, I implemented repr methods for all OTel-related FilterX objects:
- array
- kvlist
- logrecord
- resource
- scope
Additionally, I provided light tests to validate repr methods using forced string typecasting.

Add repr to FilterX Otel objects

---

lib/timeutils/tests/test_wallclocktime.c
lib/timeutils/wallclocktime.c

If the fraction of a second part does not start with a decimal dot or a digit, we just ignore it as if we parsed "0" usecs.
Comes with unit tests. @jszigetvari

timeutils/wallclocktime: make %f completely optional

---

packaging/package-indexer/remote_storage_synchronizer/s3_bucket_synchronizer.py

It seems like we need to set these on top level instead of in `client_context_params`.
This is now properly tested locally.

package-indexer: fix setting of value for integrity check

---

lib/filterx/object-datetime.c
lib/timeutils/tests/test_wallclocktime.c
lib/timeutils/wallclocktime.c
lib/timeutils/wallclocktime.h

This PR pulls the strftime() implementation from musl and exposes it using the strftime() filterx function.
This adds '%f' and the %z/%Z behaviour similar to what strptime() can easily parse.
@jszigetvari

Wallclocktime strftime

---

lib/filterx/object-dict-interface.c

`set_subscript()`, `setattr()` or `list_append()` can convert the passed value to a different `FilterXObject`, either because of a different dict/list type or in the future because of stack allocation resoluton. This is why we pass a `FilterXObject **` as the value, with it the function can show if the value was converted, and can consume the old value's reference and return a new reference to the new value.
Each `_iter()` implementation prepares and lends the key and value for the callback (`_add_elem_to_list()` in this case). Each `_iter()` implementation wants to free its own prepared key or value immediately after the iter callback call, so they do not need to know if there was a conversion. This is why the iter interface is written in a way that the callback cannot show if the key or …

filterx: fix `filterx_dict_keys()`

---

lib/filterx/filterx-object.c
lib/filterx/filterx-object.h
lib/filterx/object-json-object.c
lib/filterx/object-string.c
lib/filterx/object-string.h
lib/str-format.c
lib/str-format.h
modules/csvparser/filterx-func-parse-csv.c
modules/xml/filterx-parse-windows-eventlog-xml.c
modules/xml/filterx-parse-xml.c

This PR enables filterx code to create short-lived FilterXString instances on the stack. 
Such instances 
* clone themselves on filterx_object_ref()
* can only be unreferenced once
* free_fn() is not called (this could be changed though and is up for debate)
The PR also contains a number of conversions from allocation based FilterXString instances to these, reducing the
total number of malloc() calls significantly for unset_empties(), parse_csv() and parse_kv()

Filterx allow stack based string wrappers

---

lib/filterx/object-list-interface.c
lib/filterx/object-primitive.c
lib/filterx/object-primitive.h
lib/generic-number.c
lib/generic-number.h

Similar to #470 but this time with integer objects. It seems that we have a parse_csv() invocation with over a 100 integer
fields, so the integer cache does not cover it and I don't want to increase that cache infinitely.
This should go in after #470

Filterx allow stack based integer wrappers

---

lib/filterx/filterx-object.h
lib/filterx/object-dict-interface.c
lib/filterx/object-json-array.c
lib/filterx/object-json-object.c
lib/filterx/object-json.c
lib/filterx/object-list-interface.c
lib/filterx/tests/test_object_json.c

This may not be the best way to fix the race, but this whole caching mess will be reimplemented/removed soon.

filterx: fix racy writing of readonly JSON object caches 

---

lib/filterx/func-unset-empties.c

filterx: fix compilation error on 32-bit platforms (gsize vs. guint64)

---

lib/filterx/filterx-eval.c
lib/filterx/filterx-eval.h
lib/filterx/filterx-pipe.c
lib/filterx/filterx-scope.c
lib/filterx/filterx-scope.h
lib/filterx/filterx-variable.c
libtest/filterx-lib.c

This goes on top of #467 and brings significant performance improvements for FilterXScope

Filterx scope optimizations

---

lib/filterx/expr-variable.c

This is a small regression in #467, if we are using a $FOO and foo does not exist we will get an "error information unset", which is not very nice.

filterx fix error reporting in case a message tied variable does not exist

---

lib/filterx/filterx-scope.c
lib/filterx/filterx-scope.h
lib/filterx/func-vars.c
lib/filterx/tests/CMakeLists.txt
lib/filterx/tests/Makefile.am
lib/filterx/tests/test_scope.c

Follow-up for 145c50840708323e3f5f5bffff27f5ac72c1766a
If the GHashTable allocation appears to be costly, this can be reimplemented using a fix-sized heapqueue and a "merge" operation on the sorted variables arrays.

Fix `vars()`

---

lib/filterx/filterx-globals.c
lib/filterx/func-vars.c
lib/filterx/func-vars.h

Depens on #504
Note: `vars()` lies a little, because it formats both floating and message-tied variables, but NOT ALL message variables as they might have never appeared inside FilterX.

`vars()`: add `exclude_message_values` parameter

---

modules/json/filterx-cache-json-file.c

The race condition around json-c `get`/`put` is unsolved, but this could go in separately if reviewers agree.

Partially fix FilterX heap corruption

---

lib/filterx/func-set-fields.c
lib/filterx/func-vars.c
lib/filterx/object-string.c
lib/filterx/object-string.h

There are two patches in this PR that fix two distinct issues:
* when moving filterx_string_get_value_ref() to be inline, I removed the check for NUL termination, as all strings are NUL terminated, when constructed normally. Unfortunately stack allocated ones may rely on the explicit length without NUL termination, such as the ones in get_sdata() function.
* sometimes "-1" as an extremal value to the stack allocation macro comes in an unsigned variable, causing the check in the macro not to fire. Avoid these cases by an explicit cast.

Filterx stack based string allocation fixes

---

lib/filterx/expr-switch.c
news/fx-bugfix-527.md
tests/light/functional_tests/filterx/test_filterx_control.py

filterx: fix switch eval errors

---

lib/filterx/expr-regexp-search.c
lib/filterx/expr-regexp-subst.c
lib/filterx/tests/test_expr_regexp_search.c
lib/filterx/tests/test_expr_regexp_subst.c
tests/light/functional_tests/filterx/test_filterx.py

I don't think we need a news file entry for this.

filterx: support optimized strings in `regexp_search()` and `regexp_subst()` pattern

---

lib/CMakeLists.txt
lib/Makefile.am
lib/file-monitor.c
lib/file-monitor.h
lib/mainloop.c
modules/json/filterx-cache-json-file.c
tests/copyright/policy

Due to multiple workers, the original frozen objects must be retained until all workers have finished. Since there is currently no way to track the workers' lifecycle, we call reload, which unfreezes and releases all previously stored elements to prevent high memory usage. This is a suboptimal solution and likely temporary. The upcoming RCU feature will provide a better way to handle this issue. However, the soon-to-be-released native dictionary implementation will also support the optimal solution.

filterx: cache_json_file() inotify based automatic reload

---

scl/azure/azure-monitor.conf

The `table_name` parameter of the `azure-monitor` destination is actually referring to the stream name in the DCR, and not the table the logs end up getting written to. The actual destination table name is referenced in the DCR.
For this reason the `table_name` parameter should be rename to `stream_name`.

rename the table_name parameter of the azure monitor destination

---

modules/python-modules/syslogng/modules/webhook/scl/webhook.conf
modules/python-modules/syslogng/modules/webhook/source.py
news/feature-524.md

Depends on #523
```
webhook(port(8080) proxy-header("x-forwarded-for"));
webhook(port(8080) proxy-header(yes));
$ curl -H "x-forwarded-for: 4.3.3.2"
-H "X-Forwarded-FOR: 1.2.3.4" -X POST --data "{}" http://127.0.0.1:8080
$PEERIP: 127.0.0.1, $SOURCEIP: 1.2.3.4
```
```
webhook(port(8080) include-request-headers(yes));
filterx {
headers = json(${webhook.headers});
$type = headers["Content-Type"][-1];
$headers = headers;
};
```
$headers:
```json
{
"Host": ["127.0.0.1:8080"],
"User-Agent": ["curl/8.5.0"],
"X-Forwarded-For": [
"4.3.3.2",
"1.2.3.4"
],
"Content-Length": ["2"],
"Content-Type": ["application/x-www-form-urlencoded"]
}
```
```
$type == "application/x-www-form-urlencoded"
```

`webhook()`: proxy and headers support

---

modules/appmodel/app-transform-generator.c

For example,
```
step [sname] { $MESSAGE += " bello"; };
```
generated (transforms it into a comment):
```
```

appmodel: fix oneliner steps being ignored

---

lib/filterx/filterx-object.c

When deriving a new FilterXType, we need to inherit the original str() method, which was missing.

filterx-object: initialize str() function pointer

---

lib/filterx/object-list-interface.c
tests/light/functional_tests/filterx/test_filterx.py

This branch allows the indexing of the tail element of the list to append a new value.
e.g.
```
l = list();
l[0] = "elem";
```
Here, the assignment was not permitted previously, as the list has no elements at all, so l[0] is undefined, but this is exactly what we want to achieve, set a new one.
At the moment, addressing any other items outside of the range is still not permitted (but is in JavaScript), but that's still up for discussion.
The PR also limits the length of the arrays to 65536 elements.  We can easily increase this eventually, but I don't see use-cases where this limit would not be enough when handling logs/metrics/traces.

Filterx list allow setting the tail item by index

---

lib/filterx/expr-assign.c
lib/filterx/expr-null-coalesce.c
lib/filterx/expr-set-subscript.c
lib/filterx/expr-setattr.c
lib/filterx/filterx-error.c
lib/filterx/filterx-error.h
lib/filterx/filterx-eval.c
lib/filterx/filterx-eval.h
lib/filterx/func-set-fields.c
modules/metrics-probe/filterx/func-update-metric.c

I've extracted this from one of my longer debugger PRs (#356) to be merged separately.
This only improves the error reporting API, but does not really change how errors are emitted by filterx.

Filterx error reporting improvements

---

.github/workflows/release-light.yml
tests/light/README.md
tests/light/axosyslog_light/fixtures.py
tests/light/functional_tests/conftest.py
tests/light/pyproject.toml

Triggered either by a tag starting with "light-" or by manually on the same tags.
Based on:
https://docs.github.com/en/actions/security-for-github-actions/security-hardening-your-deployments/configuring-openid-connect-in-pypi
---
Example run: https://github.com/alltilla/axosyslog/actions/runs/13970900983

light: release workflow

---

lib/filterx/tests/test_object_string.c

Seems to be bogus, because the only case where this goes uninitialized is when the pointer to size is NULL, which is obviously not the case.
/source/lib/filterx/tests/test_object_string.c: In function ‘filterx_string_test_filterx_string_typecast_from_bytes_impl’: /source/lib/filterx/tests/test_object_string.c:122:13: warning: ‘size’ may be used uninitialized [-Wmaybe-uninitialized]
122 |   cr_assert(memcmp("001f2062797465205c73657175656e6365207f20ff", str, size) == 0);
|             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/source/lib/filterx/tests/test_object_string.c:120:9: note: ‘size’ was declared here

test_object_string: fix uninitialized variable warnings

---

lib/filterx/expr-regexp-common.c

The caller of filterx_regexp_match_eval() is responsible for "state", don't call cleanup even in the case of errors.

filterx/expr-regexp-common: don't clear the state twice

---

.astylerc
.editorconfig
news/developer-note-550.md
tests/copyright/policy

See https://editorconfig.org/ for details about the format.
I guessed on end_of_line and charset after glancing at a few files. The C/C++ settings are from .astylerc. The news settings are from news/README.md.

editorconfig: configure editors for the project's style

---

tests/light/functional_tests/filterx/test_filterx_update_metric.py
tests/light/functional_tests/source_drivers/network_source/proxyprotocol/test_pp_with_simple_tcp_connection.py
tests/light/functional_tests/tools/loggen/test_loggen_with_reconnect.py
tests/light/src/axosyslog_light/Makefile.am
tests/light/src/axosyslog_light/driver_io/file/file_io.py
tests/light/src/axosyslog_light/driver_io/network/network_io.py
tests/light/src/axosyslog_light/fixtures.py
tests/light/src/axosyslog_light/helpers/loggen/loggen.py
tests/light/src/axosyslog_light/helpers/loggen/loggen_docker_executor.py
tests/light/src/axosyslog_light/helpers/loggen/loggen_executor.py
tests/light/src/axosyslog_light/helpers/loggen/loggen_local_executor.py
tests/light/src/axosyslog_light/syslog_ng/syslog_ng.py
tests/light/src/axosyslog_light/syslog_ng/syslog_ng_docker_executor.py
tests/light/src/axosyslog_light/syslog_ng/syslog_ng_paths.py
tests/light/src/axosyslog_light/syslog_ng_config/statements/destinations/file_destination.py
tests/light/src/axosyslog_light/testcase_parameters/testcase_parameters.py

Alternative to #556 
---
The `Loggen` instance can now be instantiated with any `LoggenExecutor`, should it be `LoggenLocalExecutor` or `LoggenDockerExecutor`.
As `Loggen` is not instance specific (we can assume all syslog-ng instances have the same loggen), during the setup of the test runs, we store a `LoggenExecutor` globally from the `server` instance, and it is used for all subsequent `Loggen` constructors, if it is not overridden.
---
This PR also fixes missing `--installdir`, which can occur if we are using `docker` runner.
---
This PR also fixes a flakyness in one E2E test.
---
I have executed the E2E tests without `--installdir` with `docker` runner, and the only failing testcase is a `slog` related one, which is expected, as we cannot execute `slog` from docker right now.
Full …

light: loggen from docker

---

modules/grpc/bigquery/bigquery-worker.cpp
modules/grpc/clickhouse/clickhouse-dest-worker.cpp
modules/grpc/common/grpc-dest.cpp
modules/grpc/common/grpc-dest.h
modules/grpc/common/grpc-dest.hpp
modules/grpc/common/grpc-grammar.ym
modules/grpc/common/grpc-parser.h
modules/grpc/loki/loki-worker.cpp
modules/grpc/otel/otel-dest-worker.cpp
modules/grpc/pubsub/pubsub-dest-worker.cpp
news/feature-561.md

With this option, it is possible to fine tune how AxoSyslog behaves in case of different gRPC results.
Supported by the following destination drivers:
* `opentelemetry()`
* `loki()`
* `bigquery()`
* `clickhouse()`
* `google-pubsub-grpc()`
Supported gRPC results:
* ok
* unavailable
* cancelled
* deadline-exceeded
* aborted
* out-of-range
* data-loss
* unknown
* invalid-argument
* not-found
* already-exists
* permission-denied
* unauthenticated
* failed-precondition
* unimplemented
* internal
* resource-exhausted
Supported actions:
* disconnect
* drop
* retry
* success
Usage:
```
google-pubsub-grpc(
project("my-project")
topic("my-topic")
response-action(
not-found => disconnect
unavailable => drop
)
);
```

grpc: `response-action()`

---

.github/workflows/devshell.yml
tests/copyright/policy
tests/light/CMakeLists.txt
tests/light/Makefile.am
tests/light/poetry.lock
tests/light/pyproject.toml
tests/light/src/axosyslog_light/Makefile.am
tests/light/src/axosyslog_light/common/pytest_operations.py
tests/light/src/axosyslog_light/common/session_data.py
tests/light/src/axosyslog_light/fixtures.py
tests/light/src/axosyslog_light/helpers/loggen/loggen.py

Builds upon #562 
---
pytest-xdist does not work well with session scoped fixtures. Each runner has its own session, and no data is shared
between runners' sessions.
The introduced `SessionData` class intends to bridge this issue, by managing a session specific data storage on the disk.

light: parallel run

---

tests/copyright/policy
tests/light/pyproject.toml
tests/light/src/axosyslog_light/common/session_data.py
tests/light/src/axosyslog_light/fixtures.py
tests/light/src/axosyslog_light/syslog_ng_config/renderer.py
tests/light/src/axosyslog_light/syslog_ng_config/statements/logpath/log_context_scl_block.py
tests/light/src/axosyslog_light/syslog_ng_config/syslog_ng_config.py

Previously, the first worker to finish could remove the file while others were still running, causing race conditions.
After this commit, an active worker counter is maintained, and the file is deleted only when the counter reaches zero.
---
`LogContextSclBlocks` is useful to use things like this in the config:
```
block log foobar() {
....
};
log {
foobar(); # generating this line is now possible
};

light: `SessionData` refcount and `LogContextSclBlocks`

---

tests/light/pyproject.toml
tests/light/src/axosyslog_light/common/session_data.py
tests/light/src/axosyslog_light/fixtures.py

Sometimes with unexpected process stops (e.g. aggressively Ctrl+C'ing the test run) the `SessionData` file can stay on the file system with initialized values in it.
This commit uses the `PYTEST_XDIST_TESTRUNUID` env var, which is provided by `xdist` for workers, and is guaranteed to be unique for each run, and be the same for all workers for that run.
We store this value to the `SessionData` file, and during start if we find a file that has a different uid, we clear its contents, and start a new one.
With this we also restart the active worker count, and will be able to delete the file after the run.
---
Tested with:
* `-n12`
* `-n1`
* `-n0`
* ` `

light: work with leftover session file

---

dbld/rules

I also like to use rootless podman sometimes.
Cherry-picked from syslog-ng/syslog-ng#5326

`dbld` but without the `d`

---

tests/light/pyproject.toml
tests/light/src/axosyslog_light/syslog_ng_config/syslog_ng_config.py

The bug happened when we added the same source driver to multiple logpaths, like:
```py
source = config.create_xy_source()
config.create_logpath(statements=[source, dest_1])
config.create_logpath(statements=[source, dest_2])
```
This implicitly generated two separate source groups for `source`, which failed to start AxoSyslog.
The fix uses the `id()` function in python, which returns a unique id (pointer) to the python object, in this case the `SourceDriver`. This is not doing a real equivalence check on the object level, so if we create two separate, but identically configured sources with `config.create_xy_source()`, they will both have their respective implicitly generated source groups, but I don't think we need to optimize for this use case.

light: fix multiple implicit source groups

---

lib/filterx/object-dict.c
tests/copyright/policy
tests/light/functional_tests/Makefile.am
tests/light/functional_tests/filterx/test_filterx_dict.py

In case an item was unset() while another item with the same hash is in the dict, we erroneously reported the other item as missing as well.
The problem is that we can only break out of the lookup loop in case the index is its initial value (FXD_IX_EMPTY) and not when it is cleared (e.g. FXD_IX_DUMMY). In the latter case, we need to continue the lookup loop.
However, we should try to reuse the cleared slot for the new item. We do this by storing the first found dummy slot and returning it if we did not find any valid values in the lookup loop.

filterx/object-dict: fix unset in case of a hash collision

---

tests/light/src/axosyslog_light/syslog_ng_config/syslog_ng_config.py

It has a side effect of adding a new statement
group to the config, although it is not getting
used by anything, because the cached one is
returned.
No need to release this commit on its own, as it
is a non-functional change regarding AxoSyslog's
execution from Light.

light: do not call create_statement_group unnecessarily

---

lib/filterx/filterx-ref.c
lib/filterx/filterx-ref.h
lib/filterx/filterx-weakrefs.h

This improves copy-on-write performance for dicts by avoiding the ref/unref of dicts in the copy-on-write iteration.

Filterx: optimize dict cow

---

lib/filterx/filterx-eval.h
lib/filterx/filterx-scope.c
lib/filterx/filterx-scope.h
lib/filterx/tests/test_scope.c

Instead of immediately allocating a scratch buffer and making the message writable, delay these operations until we have
an actual value to sync back into the message.

filterx/filterx-scope: delay making the message writable in filterx_scope_sync()

---

lib/filterx/expr-assign.c
lib/filterx/expr-set-subscript.c
lib/filterx/expr-setattr.c
lib/filterx/filterx-object.h

This branch adds filterx_object_cow_fork2() function that allows us decrease the number of FilterXRef allocations (when set_subscript/setattr/assignment sees a bare, unwrapped FilterXDict or a FilterXList instance.

Filterx: add filterx_object_cow_fork2() function

---

lib/filterx/object-metrics-labels.c
news/fx-bugfix-601.md

`guint i = self->labels->len - 1` becomes a large value, instead of being `-1` if `len == 0`.
Repro config:
```
log {
source { example-msg-generator(num(1)); };
filterx {
declare labels = metrics_labels();
labels["almafa"];
};
destination{stdout();};
};
```

filterx: fix `metrics_labels` crash

---

lib/filterx/object-metrics-labels.c
tests/light/functional_tests/filterx/test_filterx_funcs.py

filterx/metrics_labels: fix crash when getting non-existent label

---

lib/filterx/object-dict.c
lib/filterx/object-string.c
lib/filterx/object-string.h

This branch adds a "hash" value to FilterXString instances, which is calculated either:
1) when the string is frozen, as that happens during compile phase, so it's cheap
2) at runtime at the first invocation (potentially racy, but should resolve itself, review required!)
This way, a hash lookup with a frozen string will avoid having to do a g_str_hash() call

Filterx cache string hash values

---

lib/filterx/filterx-object.h
lib/filterx/object-string.c
lib/filterx/object-string.h
lib/filterx/tests/test_expr_plus.c

add filterx_string_new_take() and filterx_bytes_new_type() constructors that take an already allocated buffer for the
string to avoid having to copy those bytes.

filterx: add filterx_string_new_take() and filterx_bytes_new_take() constructors

---

tests/functional/test_performance.py
tests/loggen/CMakeLists.txt
tests/loggen/Makefile.am
tests/loggen/loggen.c

```
avg_rate=99998.15 msg/s, stdev_rate=0.10%, count=1000000, time=10.0002, avg_msg_size=256, bandwidth=24999.54 KiB/s
```
Depends on #598

loggen: show standard deviation

---

modules/grpc/clickhouse/clickhouse-dest.cpp

Constructing a map with `FieldDescriptorProto::TYPE_*` produces symbols for enum values:
```
U _ZN6google8protobuf20FieldDescriptorProto11TYPE_DOUBLEE
```
This causes a linkage issue with CMake, which I couldn't resolve, but in the end, these values should not appear in the symbol table, so a `static_cast` is applied as a workaround.

clickhouse: avoid creating symbols for enum values

---

.github/workflows/test-apt-packages.yml

We now have revisions like this:
`4.11.0.new.dict.34.g0443ae7-snapshot+20250423T230904`

ci: fix apt-packages test

---

lib/filterx/expr-get-subscript.c
lib/filterx/object-string.h
tests/light/functional_tests/filterx/test_filterx_dict.py

The dict implementation uses `filterx_string_hash()` for keys, so `FilterXMessageValue` is no longer accepted.

filterx-dict: use typed string keys

---

tests/light/functional_tests/filterx/test_filterx_cache_json_file.py

Extend the `cache_json_file` tests with a create+rename style file modification
in addition to the existing plain open+write+close style one.

light: test cache_json_file with atomic move too

---

lib/filterx/CMakeLists.txt
lib/filterx/Makefile.am
lib/filterx/expr-literal-container.c
lib/filterx/expr-literal-container.h
lib/filterx/expr-literal-generator.c
lib/filterx/expr-literal-generator.h
lib/filterx/expr-literal.c
lib/filterx/filterx-grammar.ym
lib/filterx/filterx-metrics-labels.c
lib/filterx/filterx-pipe.c
lib/filterx/func-set-fields.c
lib/filterx/func-str.c
lib/filterx/func-unset-empties.c
lib/filterx/tests/test_expr_plus_generator.c
lib/filterx/tests/test_filterx_expr.c
lib/filterx/tests/test_func_unset_empties.c
lib/filterx/tests/test_metrics_labels.c
modules/cef/event-format-parser.c
modules/csvparser/filterx-func-parse-csv.c

This branch changes the handling of literal dict and list instances encountered in the source code.
Without this PRs, these were generators, e.g. we generated the values in the literal in the target fillable. With this patch, this is changed, literal dict/list instances become simple expressions that result in dict/list instances as appropriate.
This makes it possible to cache the literal dicts if all they contain are literal values.

Filterx: change literal dicts not to be generators

---

lib/filterx/object-dict.c
lib/filterx/object-dict.h
modules/csvparser/csvparser-plugin.c
modules/csvparser/filterx-func-parse-csv.c
modules/csvparser/filterx-func-parse-csv.h
modules/csvparser/tests/test_filterx_func_parse_csv.c

This turns parse_csv() from a generator to a function, returning a dict instance. It also optimizes dict allocation when
the number of columns are known.

Filterx: turn parse_csv() into a function

---

lib/filterx/filterx-eval.h
lib/filterx/filterx-globals.c
lib/filterx/filterx-globals.h
lib/filterx/filterx-object.c
lib/filterx/filterx-object.h
lib/filterx/filterx-ref.c
lib/filterx/object-dict.c
lib/filterx/object-list.c
lib/filterx/object-string.c
lib/filterx/tests/test_object_string.c

This PR changes frozen FilterXString instances so they use the same instance throughout the execution of a configuration. This deduplicates strings such as common attribute name ("meta", "name", etc), it improves memory, cache use and thereby performance.
It rounds up the allocation strategies for FilterXObject instances to 4:
* normal heap allocated/refcounted
* stack allocated
* hybernated (e.g. created at syslog-ng startup, reloads not affecting them)
* frozen (associated with configurations)
Due to setting the hash value at freeze time, this depends on #583, so I am rebasing this on top of that.

Filterx deduplicate frozen strings

---

lib/filterx/expr-variable.c
lib/filterx/filterx-scope.c
lib/filterx/object-message-value.c
lib/filterx/object-message-value.h

Instead of adding resolved macro values into our variable cache, just resolve them in place without even registering them.
This has two side effects: 
* macros are always resolved and never cached (I think this is a good thing)
* macro values are not bounced into FilterXMessageValue instances but get directly unmarshalled into a typed FilterXObject

Filterx: handle macros in expr variable

---

lib/cfg-grammar.y

For example:
https://docs.python.org/3/reference/expressions.html#operator-precedence

filterx: fix precedence and associativity of "not"

---

lib/timeutils/tests/test_wallclocktime.c
lib/timeutils/wallclocktime.c
news/bugfix-626.md

wallclocktime: strptime and strftime fixes

---

modules/python-modules/syslogng/modules/webhook/source.py
tests/copyright/policy

> In python 3.9 the event must be created inside the eventloop that will await on it
Cherry-picked from syslog-ng/syslog-ng#5372
The author is @kovgeri01, it is not visible on GitHub (probably because of the unregistered email address).

webhook: fix shutdown with older Python versions

---

lib/cfg-source.c
lib/cfg-source.h
lib/debugger/debugger.c

This is spin off from #340 to make that easier to merge. This part of the PR focuses on the interactive "list" command, which will make it easy to navigate the source code (e.g. the syslog-ng.conf file) we are debugging.

Debugger add list command

---

lib/logproto/logproto-client.h
lib/logproto/logproto-text-client.c
lib/logproto/logproto-text-client.h
lib/logwriter.c
lib/logwriter.h
lib/transport/logtransport.c
lib/transport/logtransport.h
lib/transport/transport-stack.h
lib/transport/transport-tls.c
modules/affile/logproto-file-writer.c
modules/afsocket/afinet-dest.c
modules/afsocket/afsocket-dest.c
modules/afsocket/afsocket-dest.h
modules/afsocket/afsocket-grammar.ym
news/bugfix-609-2.md
news/bugfix-609.md

Fixes the `collectd()` destination (we never read the server's response).
Fixes possible starvation issue on the destination side when reading server responses
Fixes and workarounds TLS-related state handling issues
Fixes #604

Move EOF detection and close-on-input to the proto

---

lib/compat/tests/test_strtok_r.c

This fixes an ugly superfluous warning in a test program (uninitialized value).

lib/compat: fix warning in test_strtok_r

---

lib/logproto/logproto-client.c
lib/logproto/logproto-server.c
lib/transport/logtransport.h
lib/transport/tls-context.c
lib/transport/transport-adapter.c
lib/transport/transport-adapter.h
lib/transport/transport-file.c
lib/transport/transport-socket.c
lib/transport/transport-stack.c
lib/transport/transport-stack.h
lib/transport/transport-tls.c
tests/light/src/axosyslog_light/common/network.py
tests/light/src/axosyslog_light/syslog_ng/syslog_ng_local_executor.py

This is an alternative to #632 
This is a more complete fix compared to #632 which is more like a workaround. It also fixes a few small memory leaks
in TLS connection handling.

Log transport shutdown fix

---

lib/filterx/expr-null-coalesce.c

This just extends the debug message, for a lack of a better diagnostics.

filterx/expr-null-coalesce: add more details to the null coalesce operator

---

docker/axosyslog-builder.dockerfile
docker/axosyslog.dockerfile

We should also make version tags for the builder, they could easily go out of sync due to how these jobs are scheduled.

docker: extract ALPINE_VERSION

---

lib/filterx/CMakeLists.txt
lib/filterx/Makefile.am
lib/filterx/expr-compound.c
lib/filterx/filterx-error.c
lib/filterx/filterx-error.h
lib/filterx/filterx-eval.c
lib/filterx/filterx-eval.h
lib/filterx/filterx-expr.c
lib/filterx/filterx-expr.h
lib/filterx/filterx-globals.c
lib/filterx/func-failure-info.c
lib/filterx/func-failure-info.h
lib/filterx/func-flatten.c
news/fx-feature-629.md
tests/copyright/policy
tests/light/functional_tests/Makefile.am
tests/light/functional_tests/filterx/test_filterx_failure_info.py

The following functions have been added to allow tracking failures in FilterX code:
- `failure_info_enable()`, optional parameter: `collect_falsy=true/false`, defaults to `false`:
Enable failure information collection from this point downwards through all branches of the pipeline.
- `failure_info_clear()`:
Clear accumulated failure information
- `failure_info_meta({})`:
Attach metadata to the given section of FilterX code. The metadata remains in effect until the next call
or until the end of the enclosing FilterX block, whichever comes first.
- `failure_info()`:
Return failure information as a FilterX dictionary. This should ideally be called as late as possible, for example, in the last log path of your configuration or within a fallback path.
Example output:
```
[
{
"meta": {
"step": …
```

FilterX failure info

---

lib/filterx/filterx-globals.h
lib/filterx/object-primitive.c
lib/filterx/object-primitive.h
lib/filterx/tests/test_object_integer.c

This should avoid allocation integers in the range of [-128,127)

filterx/object-primitive: add caching for small negative integers

---

lib/filterx/object-dict.c

Fixing case, when json, or dict creation crashed, if parameter was not a valid json string.
Example:
`$MSG = json("ASD");`

filterx-dict: fix crash in filterx_dict_new_from_args

---

docker/axosyslog.dockerfile

If we upgrade packages on Alpine (due to our rebuilds with CFLAGS=-fno-omit-frame-pointer), this generates a lot of junk in the image.

docker: flatten axosyslog image after it is built

---

.github/workflows/macos.yml
contrib/Brewfile

Until AxoSyslog is upgraded to the v2 API.

ci: use mongo-c-driver@1 on macOS

---

modules/grpc/pubsub/pubsub-dest-worker.cpp
news/bugfix-652.md

The message_bytes pointer was being incremented instead of updating the value it points to.  
Issue discovered by Hofi: https://github.com/syslog-ng/syslog-ng/pull/5389/commits

fix pubsub message_bytes calculation

---

tests/light/functional_tests/destination_drivers/snmp_destination/general/test_snmp_destination_missing_trap_obj.py
tests/light/functional_tests/destination_drivers/snmp_destination/general/test_snmp_destination_wrong_version.py
tests/light/functional_tests/filterx/test_filterx.py
tests/light/functional_tests/filterx/test_filterx_control.py
tests/light/functional_tests/parsers/regexp-parser/test_regexp_parser.py
tests/light/functional_tests/source_drivers/file_source/test_follow_freq_value.py
tests/light/pyproject.toml
tests/light/src/axosyslog_light/syslog_ng/console_log_reader.py
tests/light/src/axosyslog_light/syslog_ng/syslog_ng.py

After this PR:
- in case of those functional tests where we want to check if syslog-ng could not start we also check the exception error message, which help to validate more precisely why syslog-ng could not start
- Light will check syslog-ng's return code more stricter, instead of checking various patterns in stdout or stderr outputs (which can be different in various platforms).

Light: Improved crash detection

---

lib/filterx/expr-regexp-search.c
lib/filterx/object-dict.c

If the value parameter is NULL for `_format_and_append_dict_elem`, then the underlying `format_json` crashed.
Input that caused the crash:
`$MSG = regexp_search("bar", "(?<f>foo)?(?<b>bar)?");`

filterx/dict: fix crash when iterator receive NULL for value parameter

---

lib/cfg-grammar.y
lib/cfg-parser.c
lib/cfg-tree.c
lib/cfg-tree.h
lib/cfg.h
lib/logpipe.c
lib/logpipe.h
lib/logsource.c
news/feature-606.md

`log-flow-control(yes/no)` global option
This option allows enabling flow control for all log paths. When set to yes,
flow control is globally enabled, but it can still be selectively disabled
within individual log paths using the `no-flow-control` flag.
WARNING: Enabling global flow control can cause the `system()` source to block.
As a result, if messages accumulate at the destination, applications that log
through the system may become completely stalled, potentially halting their
operation. We don't recommend enabling flow control in log paths that
include the `system()` source.
For example,
```
options {
log-flow-control(yes);
};
log {
source { system(); };
destination { network("server" port(5555)); };
flags(no-flow-control);
};
log { ... };
```

`log-flow-control(yes/no)` global option

---

.github/workflows/axosyslog-nightly.yml

We no longer have -dbg variants.

ci: keep 60 days of nightly images

---

lib/filterx/filterx-scope.c

When an unset key enters FilterX, we shouldn't unset it again during sync as it can cause side-effects, for example, unsetting `PID` or `PROGRAM` may invalidate the legacy MSGHDR.

filterx-scope: avoid log_msg_unset_value() side-effects

---

modules/grpc/filterx/Makefile.am

grpc/filterx: add missing DEPENDENCIES to Makefile

---

tests/light/pyproject.toml
tests/light/src/axosyslog_light/fixtures.py

Increases the number of available non-ephemeral
ports.

light: use lower initial value for port allocator

---

lib/stats/stats-prometheus.c
news/other-715.md

Stale counters will be shown in order not to lose information, for example,
when messages are sent using short-lived connections and metrics are scraped in
minute intervals.
We recommend using `syslog-ng-ctl stats --remove-orphans` during each configuration reload,
but only after the values of those metrics have been scraped by all scrapers.

`syslog-ng-ctl stats prometheus`: show orphan metrics

---

news/feature-709.md
tests/light/functional_tests/source_drivers/network_source/test_client_port.py
tests/light/src/axosyslog_light/driver_io/network/network_io.py
tests/light/src/axosyslog_light/helpers/loggen/loggen_executor.py
tests/light/src/axosyslog_light/syslog_ng_config/statements/sources/network_source.py
tests/light/src/axosyslog_light/syslog_ng_config/statements/sources/syslog_source.py
tests/loggen/loggen.c
tests/loggen/loggen_helper.c
tests/loggen/loggen_helper.h
tests/loggen/loggen_plugin.h
tests/loggen/socket_plugin/socket_plugin.c
tests/loggen/ssl_plugin/ssl_plugin.c

It is useful if we want to control which outbounds
port is used to avoid possible collisions with
server ports.

`loggen`: add `--client-port`

---

lib/filterx/CMakeLists.txt
lib/filterx/Makefile.am
lib/filterx/expr-string-operators.c
lib/filterx/expr-string-operators.h
lib/filterx/filterx-grammar.ym
news/fx-feature-720.md
tests/light/functional_tests/filterx/test_filterx.py

For example:
```
filterx {
str = "example";
idx = 3;
str[idx..5] == "mp";
str[..idx] == "exa";
str[idx..] == "mple";
};
```

filterx: add string slicing operator 

---

modules/xml/filterx-func-format-windows-eventlog-xml.c
modules/xml/filterx-parse-windows-eventlog-xml.c
news/fx-bugfix-722.md
tests/light/functional_tests/filterx/test_filterx.py

In case of the following input:
```
<EventData>
<Data Name="SubjectUserSid">S-1-5-18</Data>
<Data Name="SubjectUserName">WIN-GG82ULGC9GO$</Data>
<Data Name="SubjectDomainName">CONTOSO</Data>
<Data Name="SubjectLogonId">0x3e7</Data>
<Data Name="NewProcessId">0x2bc</Data>
<Data Name="NewProcessName">C:\Windows\System32\rundll32.exe</Data>
<Data Name="TokenElevationType">%%1938</Data>
<Data Name="ProcessId">0xe74</Data>
<Data Name="CommandLine" />
<Data Name="TargetUserSid">S-1-5-21-1377283216-344919071-3415362939-1104</Data>
<Data Name="TargetUserName">dadmin</Data>
<Data Name="TargetDomainName">CONTOSO</Data>
<Data Name="TargetLogonId">0x4a5af0</Data>
<Data Name="ParentProcessName">C:\Windows\explorer.exe</Data>
<Data Name="MandatoryLabel">S-1-16-8192</Data>
</EventData>
```
Previously the …

Filterx fix parse and format windows eventlog xml functions

---

modules/appmodel/app-parser-generator.c
tests/light/functional_tests/parsers/app-parser/test_app_parser.py

A common pattern is to call inner app-parsers from app adapters. In this case the outer adapter
"relay"s the filtering of the message to the inner topic's adapters, so it should not overwrite the
filterx-app-variable() set by the inner adapter.

modules/appmodel: do not overwrite filterx-app-variable() if it is already set

---

modules/http/http-grammar.ym
modules/http/http-worker.c
modules/http/http.c
modules/http/http.h
modules/http/tests/test_http-signal_slot.c
news/feature-731.md

In case of batching the templates in `body-prefix()` will be calculated from the first message. Make sure to use `worker-partition-key()` to group similar messages together.
Literal dollar signs (`$`) used in `body-prefix()` must be escaped like `$$`.
Example usage:
```
http(
...
body-prefix('{"log_type": "$log_type", "entries": [')
body('"$MSG"')
delimiter(",")
body-suffix("]}")
batch-lines(1000)
batch-timeout(1000)
worker-partition-key("$log_type")
);
```

`http`: support templating in `body-prefix()`

---

tests/light/pyproject.toml
tests/light/src/axosyslog_light/driver_io/network/network_io.py

light: fix sending unicode characters through framed syslog

---

modules/grpc/common/credentials/grpc-credentials-builder.cpp
modules/grpc/common/credentials/grpc-credentials-builder.h
modules/grpc/common/credentials/grpc-credentials-builder.hpp
modules/grpc/common/grpc-grammar.ym
modules/grpc/common/grpc-parser.h
news/feature-732.md

Example usage:
```
destination {
google-pubsub-grpc(
project("test")
topic("test")
auth(adc(service-account-key("absolute path to file")))
);
};
```

Add ADC credentials option

---

lib/cfg-grammar.y
lib/cfg-lex.l
lib/filterx/expr-assign.c
lib/filterx/expr-literal-container.c
lib/filterx/expr-literal-container.h
lib/filterx/expr-set-subscript.c
lib/filterx/expr-setattr.c
lib/filterx/filterx-grammar.ym
news/fx-feature-736.md
tests/light/functional_tests/filterx/test_filterx_dict.py

For example, the following fields won't be set:
```
$MSG = {
"nullidontwant":?? null,
"erroridontwant":?? nonexistingvar,
};
```

FilterX: null and error-safe dict elements

---

modules/xml/filterx-func-format-windows-eventlog-xml.c
modules/xml/filterx-func-format-xml.c
news/fx-bugfix-743.md
tests/light/functional_tests/filterx/test_filterx.py

FilterX: fix escaping in format_xml and format_windows_eventlog_xml functions

---

modules/xml/filterx-parse-windows-eventlog-xml.c

I tried to parse a sample of Windows  Eventlog XML and I didn't get an error message, which took me a while to recognize.
I used an incorrect sample, which I didn't realize. This should make it easier to find these cases.

modules/xml: add error message on missing xmlns attribute

---

lib/cfg-grammar.y
lib/logthrdest/logthrdestdrv.c
news/bugfix-753.md
scl/google/google-pubsub.conf
scl/logscale/logscale.conf
scl/openobserve/openobserve.conf
scl/splunk/splunk.conf

log-iw-size()/max-connections() had to be greater than batch-lines()*workers() when flow-control was enabled, otherwise message delivery was slowed down artificially.
The given source stopped reading messages because of flow-control, but the destination didn't ack messages because it was waiting for the batch to be complete. After batch-timeout() milliseconds, the batch was finally sent out, and this repeated again and again.

logthrdest: fix slow destinations when flow-control is "misconfigured"

---

lib/filterx/expr-membership.c
news/fx-bugfix-759.md

Fixing crash, that could occur when the following syntax is used:
For example:
```
if ("cica" in ["asd", "2", "cica"]) {
$MSG = "YES";
};
```

Filterx/membership: fix in operator crash

---

modules/kvformat/filterx-func-parse-kv.c
modules/kvformat/filterx-func-parse-kv.h
news/feature-770.md

FilterX `parse_kv()`: add stray_words_append_to_value flag
For example,
```
filterx {
$MSG = parse_kv($MSG, value_separator="=", pair_separator=" ", stray_words_append_to_value=true);
};
input: a=b b=c d e f=g
output: {"a":"b","b":"c d e","f":"g"}
```

filterx-parse-kv: add stray_words_append_to_value mode

---

lib/cfg-lex.l
news/bugfix-776.md
tests/light/functional_tests/filterx/test_filterx.py

Let's redefine what slash_string means in order to make the escaping rules
clear:
Everything between two / characters are treated literally, except for `\/`,
which can be used to include a `/` character within the string.
If you want to include `\/` within the string, you can do that too: `\\/`
This type of string literal syntax can be used to construct regexp
patterns.
pcre2 handles special non-printing characters (`\r`, `\n`, `\t`, etc.),
octals (`\oDDD`), and hex as well (`\xDD`), so no need to escape those in our
lexer.
Note: it is not possible to represent strings that end with a single `\`
but that would be an invalid regexp, so this limitation is acceptable.

Fix slashstring

---

modules/afprog/afprog.c
news/bugfix-779.md

Cherry-picked from syslog-ng/syslog-ng#5445
This is an excellent catch and fix from @beni-atlnz.
It doesn't cause invalid reads or a crash in case of AxoSyslog (we don't have `cfg_tree_register_initialized_pipe()`), but we shouldn't keep a pointer to a freed configuration anyway.

Fix invalid access of freed log-writer cfg

---

charts/axosyslog/Chart.yaml
charts/axosyslog/README.md
charts/axosyslog/templates/syslog-statefulset.yaml
charts/axosyslog/values.yaml

The helm chart now supports adding extra volumes to the syslog sts.
Tested it, resulting in the following:
```yaml
volumeMounts:
- mountPath: /etc/syslog-ng/syslog-ng.conf
name: config
subPath: syslog-ng.conf
- mountPath: /shared
name: shared-storage
dnsPolicy: ClusterFirst
restartPolicy: Always
schedulerName: default-scheduler
securityContext: {}
terminationGracePeriodSeconds: 30
volumes:
- configMap:
defaultMode: 420
name: axosyslog-syslog
name: config
- name: shared-storage
persistentVolumeClaim:
claimName: axosyslog-shared-pvc
```
values.yaml snippet:
```yaml
syslog:
enabled: true
extraVolumeMounts:
- name: shared-storage
mountPath: /shared
extraVolumes:
- name: shared-storage
persistentVolumeClaim:
claimName: axosyslog-shared-pvc
```
TODO:

charts: add extraVolumes / extraVolumeMounts to syslog sts

---

lib/cfg-grammar.y
lib/filterx/expr-arithmetic-operators.c
lib/filterx/expr-arithmetic-operators.h
lib/filterx/filterx-grammar.ym
news/feature-788.md

Useful for dynamic string slicing, for example:
```
str[..-tempvar]
```

filterx: implement unary minus and plus operators

---

lib/filterx/expr-membership.c
news/bugfix-791.md
tests/light/functional_tests/filterx/test_filterx.py

filterx/expr-membership: fix finding message_values in arrays 

---

lib/filterx/filterx-object.c
lib/filterx/filterx-object.h

Without:
bazsi@bzorp3:~/src/syslog-ng/syslog-ng$ time for i in `seq 1 200`; do cat dbld/install/pan_dump.txt ; done | nc -q0 localhost 2000
real	0m8.156s
With:
bazsi@bzorp3:~/src/syslog-ng/syslog-ng$ time for i in `seq 1 200`; do cat dbld/install/pan_dump.txt ; done | nc -q0 localhost 2000
real	0m8.083s

Filterx: inline filterx_object_init_instance()

---

lib/timeutils/tests/test_wallclocktime.c
lib/timeutils/wallclocktime.c
news/bugfix-811.md

timeutils/wallclocktime: fix strftime for %Z 
